//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/charset/MalformedInputException.java
//

#ifndef _JavaNioCharsetMalformedInputException_H_
#define _JavaNioCharsetMalformedInputException_H_

#include "J2ObjC_header.h"
#include "java/nio/charset/CharacterCodingException.h"

@interface JavaNioCharsetMalformedInputException : JavaNioCharsetCharacterCodingException

#pragma mark Public

- (instancetype)initWithInt:(jint)length;

- (jint)getInputLength;

- (NSString *)getMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioCharsetMalformedInputException)

FOUNDATION_EXPORT void JavaNioCharsetMalformedInputException_initWithInt_(JavaNioCharsetMalformedInputException *self, jint length);

FOUNDATION_EXPORT JavaNioCharsetMalformedInputException *new_JavaNioCharsetMalformedInputException_initWithInt_(jint length) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioCharsetMalformedInputException)

#endif // _JavaNioCharsetMalformedInputException_H_
