//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/validation/SchemaFactoryLoader.java
//

#ifndef _JavaxXmlValidationSchemaFactoryLoader_H_
#define _JavaxXmlValidationSchemaFactoryLoader_H_

#include "J2ObjC_header.h"

@class JavaxXmlValidationSchemaFactory;

@interface JavaxXmlValidationSchemaFactoryLoader : NSObject

#pragma mark Public

- (JavaxXmlValidationSchemaFactory *)newFactoryWithNSString:(NSString *)schemaLanguage OBJC_METHOD_FAMILY_NONE;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlValidationSchemaFactoryLoader)

FOUNDATION_EXPORT void JavaxXmlValidationSchemaFactoryLoader_init(JavaxXmlValidationSchemaFactoryLoader *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlValidationSchemaFactoryLoader)

#endif // _JavaxXmlValidationSchemaFactoryLoader_H_
