//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/validation/SchemaFactory.java
//

#ifndef _JavaxXmlValidationSchemaFactory_H_
#define _JavaxXmlValidationSchemaFactory_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaIoFile;
@class JavaLangClassLoader;
@class JavaNetURL;
@class JavaxXmlValidationSchema;
@protocol JavaxXmlTransformSource;
@protocol OrgW3cDomLsLSResourceResolver;
@protocol OrgXmlSaxErrorHandler;

@interface JavaxXmlValidationSchemaFactory : NSObject

#pragma mark Public

- (id<OrgXmlSaxErrorHandler>)getErrorHandler;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (id)getPropertyWithNSString:(NSString *)name;

- (id<OrgW3cDomLsLSResourceResolver>)getResourceResolver;

- (jboolean)isSchemaLanguageSupportedWithNSString:(NSString *)schemaLanguage;

+ (JavaxXmlValidationSchemaFactory *)newInstanceWithNSString:(NSString *)schemaLanguage OBJC_METHOD_FAMILY_NONE;

+ (JavaxXmlValidationSchemaFactory *)newInstanceWithNSString:(NSString *)schemaLanguage
                                                withNSString:(NSString *)factoryClassName
                                     withJavaLangClassLoader:(JavaLangClassLoader *)classLoader OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlValidationSchema *)newSchema OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlValidationSchema *)newSchemaWithJavaIoFile:(JavaIoFile *)schema OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlValidationSchema *)newSchemaWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)schema OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlValidationSchema *)newSchemaWithJavaxXmlTransformSourceArray:(IOSObjectArray *)schemas OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlValidationSchema *)newSchemaWithJavaNetURL:(JavaNetURL *)schema OBJC_METHOD_FAMILY_NONE;

- (void)setErrorHandlerWithOrgXmlSaxErrorHandler:(id<OrgXmlSaxErrorHandler>)errorHandler;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (void)setPropertyWithNSString:(NSString *)name
                         withId:(id)object;

- (void)setResourceResolverWithOrgW3cDomLsLSResourceResolver:(id<OrgW3cDomLsLSResourceResolver>)resourceResolver;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlValidationSchemaFactory)

FOUNDATION_EXPORT void JavaxXmlValidationSchemaFactory_init(JavaxXmlValidationSchemaFactory *self);

FOUNDATION_EXPORT JavaxXmlValidationSchemaFactory *JavaxXmlValidationSchemaFactory_newInstanceWithNSString_(NSString *schemaLanguage);

FOUNDATION_EXPORT JavaxXmlValidationSchemaFactory *JavaxXmlValidationSchemaFactory_newInstanceWithNSString_withNSString_withJavaLangClassLoader_(NSString *schemaLanguage, NSString *factoryClassName, JavaLangClassLoader *classLoader);

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlValidationSchemaFactory)

#endif // _JavaxXmlValidationSchemaFactory_H_
