//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/util/MapPositionUtil.java
//

#ifndef _OrgMapsforgeMapUtilMapPositionUtil_H_
#define _OrgMapsforgeMapUtilMapPositionUtil_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeCoreModelMapPosition;
@class OrgMapsforgeCoreModelPoint;

@interface OrgMapsforgeMapUtilMapPositionUtil : NSObject

#pragma mark Public

+ (OrgMapsforgeCoreModelBoundingBox *)getBoundingBoxWithOrgMapsforgeCoreModelMapPosition:(OrgMapsforgeCoreModelMapPosition *)mapPosition
                                                      withOrgMapsforgeCoreModelDimension:(OrgMapsforgeCoreModelDimension *)canvasDimension
                                                                                 withInt:(jint)tileSize;

+ (OrgMapsforgeCoreModelPoint *)getTopLeftPointWithOrgMapsforgeCoreModelMapPosition:(OrgMapsforgeCoreModelMapPosition *)mapPosition
                                                 withOrgMapsforgeCoreModelDimension:(OrgMapsforgeCoreModelDimension *)canvasDimension
                                                                            withInt:(jint)tileSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapUtilMapPositionUtil)

FOUNDATION_EXPORT OrgMapsforgeCoreModelBoundingBox *OrgMapsforgeMapUtilMapPositionUtil_getBoundingBoxWithOrgMapsforgeCoreModelMapPosition_withOrgMapsforgeCoreModelDimension_withInt_(OrgMapsforgeCoreModelMapPosition *mapPosition, OrgMapsforgeCoreModelDimension *canvasDimension, jint tileSize);

FOUNDATION_EXPORT OrgMapsforgeCoreModelPoint *OrgMapsforgeMapUtilMapPositionUtil_getTopLeftPointWithOrgMapsforgeCoreModelMapPosition_withOrgMapsforgeCoreModelDimension_withInt_(OrgMapsforgeCoreModelMapPosition *mapPosition, OrgMapsforgeCoreModelDimension *canvasDimension, jint tileSize);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapUtilMapPositionUtil)

#endif // _OrgMapsforgeMapUtilMapPositionUtil_H_
