//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/util/MapViewProjection.java
//

#ifndef _OrgMapsforgeMapUtilMapViewProjection_H_
#define _OrgMapsforgeMapUtilMapViewProjection_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelPoint;
@protocol OrgMapsforgeMapViewMapView;

@interface OrgMapsforgeMapUtilMapViewProjection : NSObject

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapViewMapView:(id<OrgMapsforgeMapViewMapView>)mapView;

- (OrgMapsforgeCoreModelLatLong *)fromPixelsWithDouble:(jdouble)x
                                            withDouble:(jdouble)y;

- (jdouble)getLatitudeSpan;

- (jdouble)getLongitudeSpan;

- (OrgMapsforgeCoreModelPoint *)toPixelsWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)inArg;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapUtilMapViewProjection)

FOUNDATION_EXPORT void OrgMapsforgeMapUtilMapViewProjection_initWithOrgMapsforgeMapViewMapView_(OrgMapsforgeMapUtilMapViewProjection *self, id<OrgMapsforgeMapViewMapView> mapView);

FOUNDATION_EXPORT OrgMapsforgeMapUtilMapViewProjection *new_OrgMapsforgeMapUtilMapViewProjection_initWithOrgMapsforgeMapViewMapView_(id<OrgMapsforgeMapViewMapView> mapView) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapUtilMapViewProjection)

#endif // _OrgMapsforgeMapUtilMapViewProjection_H_
