//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/InterruptedException.java
//

#ifndef _JavaLangInterruptedException_H_
#define _JavaLangInterruptedException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

@interface JavaLangInterruptedException : JavaLangException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangInterruptedException)

FOUNDATION_EXPORT void JavaLangInterruptedException_init(JavaLangInterruptedException *self);

FOUNDATION_EXPORT JavaLangInterruptedException *new_JavaLangInterruptedException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaLangInterruptedException_initWithNSString_(JavaLangInterruptedException *self, NSString *detailMessage);

FOUNDATION_EXPORT JavaLangInterruptedException *new_JavaLangInterruptedException_initWithNSString_(NSString *detailMessage) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangInterruptedException)

#endif // _JavaLangInterruptedException_H_
