//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/NegativeArraySizeException.java
//

#ifndef _JavaLangNegativeArraySizeException_H_
#define _JavaLangNegativeArraySizeException_H_

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

@interface JavaLangNegativeArraySizeException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangNegativeArraySizeException)

FOUNDATION_EXPORT void JavaLangNegativeArraySizeException_init(JavaLangNegativeArraySizeException *self);

FOUNDATION_EXPORT JavaLangNegativeArraySizeException *new_JavaLangNegativeArraySizeException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaLangNegativeArraySizeException_initWithNSString_(JavaLangNegativeArraySizeException *self, NSString *detailMessage);

FOUNDATION_EXPORT JavaLangNegativeArraySizeException *new_JavaLangNegativeArraySizeException_initWithNSString_(NSString *detailMessage) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangNegativeArraySizeException)

#endif // _JavaLangNegativeArraySizeException_H_
