//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/NoClassDefFoundError.java
//

#ifndef _JavaLangNoClassDefFoundError_H_
#define _JavaLangNoClassDefFoundError_H_

#include "J2ObjC_header.h"
#include "java/lang/LinkageError.h"

@interface JavaLangNoClassDefFoundError : JavaLangLinkageError

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangNoClassDefFoundError)

FOUNDATION_EXPORT void JavaLangNoClassDefFoundError_init(JavaLangNoClassDefFoundError *self);

FOUNDATION_EXPORT JavaLangNoClassDefFoundError *new_JavaLangNoClassDefFoundError_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaLangNoClassDefFoundError_initWithNSString_(JavaLangNoClassDefFoundError *self, NSString *detailMessage);

FOUNDATION_EXPORT JavaLangNoClassDefFoundError *new_JavaLangNoClassDefFoundError_initWithNSString_(NSString *detailMessage) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangNoClassDefFoundError)

#endif // _JavaLangNoClassDefFoundError_H_
