//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/header/MapFileException.java
//

#ifndef _OrgMapsforgeMapReaderHeaderMapFileException_H_
#define _OrgMapsforgeMapReaderHeaderMapFileException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalArgumentException.h"

@interface OrgMapsforgeMapReaderHeaderMapFileException : JavaLangIllegalArgumentException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)errorMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderHeaderMapFileException)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderHeaderMapFileException_initWithNSString_(OrgMapsforgeMapReaderHeaderMapFileException *self, NSString *errorMessage);

FOUNDATION_EXPORT OrgMapsforgeMapReaderHeaderMapFileException *new_OrgMapsforgeMapReaderHeaderMapFileException_initWithNSString_(NSString *errorMessage) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderHeaderMapFileException)

#endif // _OrgMapsforgeMapReaderHeaderMapFileException_H_
