//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/auth/Destroyable.java
//

#ifndef _JavaxSecurityAuthDestroyable_H_
#define _JavaxSecurityAuthDestroyable_H_

#include "J2ObjC_header.h"

@protocol JavaxSecurityAuthDestroyable < NSObject, JavaObject >

- (void)destroy;

- (jboolean)isDestroyed;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityAuthDestroyable)

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityAuthDestroyable)

#endif // _JavaxSecurityAuthDestroyable_H_
