//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/junit/build_result/java/org/junit/runners/model/FrameworkMember.java
//

#ifndef _OrgJunitRunnersModelFrameworkMember_H_
#define _OrgJunitRunnersModelFrameworkMember_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@protocol JavaUtilList;

@interface OrgJunitRunnersModelFrameworkMember : NSObject

#pragma mark Package-Private

- (instancetype)init;

- (IOSObjectArray *)getAnnotations;

- (jboolean)isShadowedByWithJavaUtilList:(id<JavaUtilList>)members;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)otherMember;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelFrameworkMember)

FOUNDATION_EXPORT void OrgJunitRunnersModelFrameworkMember_init(OrgJunitRunnersModelFrameworkMember *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelFrameworkMember)

#endif // _OrgJunitRunnersModelFrameworkMember_H_
