//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/cache/TwoLevelTileCache.java
//

#ifndef _OrgMapsforgeMapLayerCacheTwoLevelTileCache_H_
#define _OrgMapsforgeMapLayerCacheTwoLevelTileCache_H_

#include "J2ObjC_header.h"
#include "org/mapsforge/map/layer/cache/TileCache.h"

@class OrgMapsforgeMapLayerQueueJob;
@protocol JavaUtilSet;
@protocol OrgMapsforgeCoreGraphicsTileBitmap;

@interface OrgMapsforgeMapLayerCacheTwoLevelTileCache : NSObject < OrgMapsforgeMapLayerCacheTileCache >

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapLayerCacheTileCache:(id<OrgMapsforgeMapLayerCacheTileCache>)firstLevelTileCache
                    withOrgMapsforgeMapLayerCacheTileCache:(id<OrgMapsforgeMapLayerCacheTileCache>)secondLevelTileCache;

- (jboolean)containsKeyWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)key;

- (void)destroy;

- (id<OrgMapsforgeCoreGraphicsTileBitmap>)getWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)key;

- (jint)getCapacity;

- (jint)getCapacityFirstLevel;

- (id<OrgMapsforgeCoreGraphicsTileBitmap>)getImmediatelyWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)key;

- (void)purge;

- (void)putWithOrgMapsforgeMapLayerQueueJob:(OrgMapsforgeMapLayerQueueJob *)key
     withOrgMapsforgeCoreGraphicsTileBitmap:(id<OrgMapsforgeCoreGraphicsTileBitmap>)bitmap;

- (void)setWorkingSetWithJavaUtilSet:(id<JavaUtilSet>)newWorkingSet;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerCacheTwoLevelTileCache)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerCacheTwoLevelTileCache_initWithOrgMapsforgeMapLayerCacheTileCache_withOrgMapsforgeMapLayerCacheTileCache_(OrgMapsforgeMapLayerCacheTwoLevelTileCache *self, id<OrgMapsforgeMapLayerCacheTileCache> firstLevelTileCache, id<OrgMapsforgeMapLayerCacheTileCache> secondLevelTileCache);

FOUNDATION_EXPORT OrgMapsforgeMapLayerCacheTwoLevelTileCache *new_OrgMapsforgeMapLayerCacheTwoLevelTileCache_initWithOrgMapsforgeMapLayerCacheTileCache_withOrgMapsforgeMapLayerCacheTileCache_(id<OrgMapsforgeMapLayerCacheTileCache> firstLevelTileCache, id<OrgMapsforgeMapLayerCacheTileCache> secondLevelTileCache) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerCacheTwoLevelTileCache)

#endif // _OrgMapsforgeMapLayerCacheTwoLevelTileCache_H_
