//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/atomic/AtomicReferenceArray.java
//

#ifndef _JavaUtilConcurrentAtomicAtomicReferenceArray_H_
#define _JavaUtilConcurrentAtomicAtomicReferenceArray_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSObjectArray;

@interface JavaUtilConcurrentAtomicAtomicReferenceArray : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithNSObjectArray:(IOSObjectArray *)array;

- (instancetype)initWithInt:(jint)length;

- (jboolean)compareAndSetWithInt:(jint)i
                          withId:(id)expect
                          withId:(id)update;

- (id)getWithInt:(jint)i;

- (id)getAndSetWithInt:(jint)i
                withId:(id)newValue;

- (void)lazySetWithInt:(jint)i
                withId:(id)newValue;

- (jint)length;

- (void)setWithInt:(jint)i
            withId:(id)newValue;

- (NSString *)description;

- (jboolean)weakCompareAndSetWithInt:(jint)i
                              withId:(id)expect
                              withId:(id)update;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilConcurrentAtomicAtomicReferenceArray)

FOUNDATION_EXPORT void JavaUtilConcurrentAtomicAtomicReferenceArray_initWithInt_(JavaUtilConcurrentAtomicAtomicReferenceArray *self, jint length);

FOUNDATION_EXPORT JavaUtilConcurrentAtomicAtomicReferenceArray *new_JavaUtilConcurrentAtomicAtomicReferenceArray_initWithInt_(jint length) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilConcurrentAtomicAtomicReferenceArray_initWithNSObjectArray_(JavaUtilConcurrentAtomicAtomicReferenceArray *self, IOSObjectArray *array);

FOUNDATION_EXPORT JavaUtilConcurrentAtomicAtomicReferenceArray *new_JavaUtilConcurrentAtomicAtomicReferenceArray_initWithNSObjectArray_(IOSObjectArray *array) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilConcurrentAtomicAtomicReferenceArray)

#endif // _JavaUtilConcurrentAtomicAtomicReferenceArray_H_
