//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/datatype/XMLGregorianCalendar.java
//

#ifndef _JavaxXmlDatatypeXMLGregorianCalendar_H_
#define _JavaxXmlDatatypeXMLGregorianCalendar_H_

#include "J2ObjC_header.h"

@class JavaMathBigDecimal;
@class JavaMathBigInteger;
@class JavaUtilGregorianCalendar;
@class JavaUtilLocale;
@class JavaUtilTimeZone;
@class JavaxXmlDatatypeDuration;
@class JavaxXmlNamespaceQName;

@interface JavaxXmlDatatypeXMLGregorianCalendar : NSObject < NSCopying >

#pragma mark Public

- (instancetype)init;

- (void)addWithJavaxXmlDatatypeDuration:(JavaxXmlDatatypeDuration *)duration;

- (void)clear;

- (id)clone;

- (jint)compareWithJavaxXmlDatatypeXMLGregorianCalendar:(JavaxXmlDatatypeXMLGregorianCalendar *)xmlGregorianCalendar;

- (jboolean)isEqual:(id)obj;

- (jint)getDay;

- (JavaMathBigInteger *)getEon;

- (JavaMathBigInteger *)getEonAndYear;

- (JavaMathBigDecimal *)getFractionalSecond;

- (jint)getHour;

- (jint)getMillisecond;

- (jint)getMinute;

- (jint)getMonth;

- (jint)getSecond;

- (jint)getTimezone;

- (JavaUtilTimeZone *)getTimeZoneWithInt:(jint)defaultZoneoffset;

- (JavaxXmlNamespaceQName *)getXMLSchemaType;

- (jint)getYear;

- (NSUInteger)hash;

- (jboolean)isValid;

- (JavaxXmlDatatypeXMLGregorianCalendar *)normalize;

- (void)reset;

- (void)setDayWithInt:(jint)day;

- (void)setFractionalSecondWithJavaMathBigDecimal:(JavaMathBigDecimal *)fractional;

- (void)setHourWithInt:(jint)hour;

- (void)setMillisecondWithInt:(jint)millisecond;

- (void)setMinuteWithInt:(jint)minute;

- (void)setMonthWithInt:(jint)month;

- (void)setSecondWithInt:(jint)second;

- (void)setTimeWithInt:(jint)hour
               withInt:(jint)minute
               withInt:(jint)second;

- (void)setTimeWithInt:(jint)hour
               withInt:(jint)minute
               withInt:(jint)second
withJavaMathBigDecimal:(JavaMathBigDecimal *)fractional;

- (void)setTimeWithInt:(jint)hour
               withInt:(jint)minute
               withInt:(jint)second
               withInt:(jint)millisecond;

- (void)setTimezoneWithInt:(jint)offset;

- (void)setYearWithJavaMathBigInteger:(JavaMathBigInteger *)year;

- (void)setYearWithInt:(jint)year;

- (JavaUtilGregorianCalendar *)toGregorianCalendar;

- (JavaUtilGregorianCalendar *)toGregorianCalendarWithJavaUtilTimeZone:(JavaUtilTimeZone *)timezone
                                                    withJavaUtilLocale:(JavaUtilLocale *)aLocale
                              withJavaxXmlDatatypeXMLGregorianCalendar:(JavaxXmlDatatypeXMLGregorianCalendar *)defaults;

- (NSString *)description;

- (NSString *)toXMLFormat;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlDatatypeXMLGregorianCalendar)

FOUNDATION_EXPORT void JavaxXmlDatatypeXMLGregorianCalendar_init(JavaxXmlDatatypeXMLGregorianCalendar *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlDatatypeXMLGregorianCalendar)

#endif // _JavaxXmlDatatypeXMLGregorianCalendar_H_
