//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/junit/build_result/java/org/hamcrest/core/AnyOf.java
//

#ifndef _OrgHamcrestCoreAnyOf_H_
#define _OrgHamcrestCoreAnyOf_H_

#include "J2ObjC_header.h"
#include "org/hamcrest/BaseMatcher.h"

@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

@interface OrgHamcrestCoreAnyOf : OrgHamcrestBaseMatcher

#pragma mark Public

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)matchers;

+ (id<OrgHamcrestMatcher>)anyOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

+ (id<OrgHamcrestMatcher>)anyOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (jboolean)matchesWithId:(id)o;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestCoreAnyOf)

FOUNDATION_EXPORT void OrgHamcrestCoreAnyOf_initWithJavaLangIterable_(OrgHamcrestCoreAnyOf *self, id<JavaLangIterable> matchers);

FOUNDATION_EXPORT OrgHamcrestCoreAnyOf *new_OrgHamcrestCoreAnyOf_initWithJavaLangIterable_(id<JavaLangIterable> matchers) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreAnyOf_anyOfWithOrgHamcrestMatcherArray_(IOSObjectArray *matchers);

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreAnyOf_anyOfWithJavaLangIterable_(id<JavaLangIterable> matchers);

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCoreAnyOf)

#endif // _OrgHamcrestCoreAnyOf_H_
