//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/junit/build_result/java/org/hamcrest/core/IsAnything.java
//

#ifndef _OrgHamcrestCoreIsAnything_H_
#define _OrgHamcrestCoreIsAnything_H_

#include "J2ObjC_header.h"
#include "org/hamcrest/BaseMatcher.h"

@class IOSClass;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

@interface OrgHamcrestCoreIsAnything : OrgHamcrestBaseMatcher

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)description_;

+ (id<OrgHamcrestMatcher>)anyWithIOSClass:(IOSClass *)type;

+ (id<OrgHamcrestMatcher>)anything;

+ (id<OrgHamcrestMatcher>)anythingWithNSString:(NSString *)description_;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (jboolean)matchesWithId:(id)o;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestCoreIsAnything)

FOUNDATION_EXPORT void OrgHamcrestCoreIsAnything_init(OrgHamcrestCoreIsAnything *self);

FOUNDATION_EXPORT OrgHamcrestCoreIsAnything *new_OrgHamcrestCoreIsAnything_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgHamcrestCoreIsAnything_initWithNSString_(OrgHamcrestCoreIsAnything *self, NSString *description_);

FOUNDATION_EXPORT OrgHamcrestCoreIsAnything *new_OrgHamcrestCoreIsAnything_initWithNSString_(NSString *description_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIsAnything_anything();

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIsAnything_anythingWithNSString_(NSString *description_);

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreIsAnything_anyWithIOSClass_(IOSClass *type);

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCoreIsAnything)

#endif // _OrgHamcrestCoreIsAnything_H_
