//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/AbstractQueue.java
//

#ifndef _JavaUtilAbstractQueue_H_
#define _JavaUtilAbstractQueue_H_

#include "J2ObjC_header.h"
#include "java/util/AbstractCollection.h"
#include "java/util/Queue.h"

@protocol JavaUtilCollection;

@interface JavaUtilAbstractQueue : JavaUtilAbstractCollection < JavaUtilQueue >

#pragma mark Public

- (jboolean)addWithId:(id)e;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (void)clear;

- (id)element;

- (id)remove;

#pragma mark Protected

- (instancetype)init;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilAbstractQueue)

FOUNDATION_EXPORT void JavaUtilAbstractQueue_init(JavaUtilAbstractQueue *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilAbstractQueue)

#endif // _JavaUtilAbstractQueue_H_
