//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/EventObject.java
//

#ifndef _JavaUtilEventObject_H_
#define _JavaUtilEventObject_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface JavaUtilEventObject : NSObject < JavaIoSerializable > {
 @public
  id source_;
}

#pragma mark Public

- (instancetype)initWithId:(id)source;

- (id)getSource;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilEventObject)

J2OBJC_FIELD_SETTER(JavaUtilEventObject, source_, id)

FOUNDATION_EXPORT void JavaUtilEventObject_initWithId_(JavaUtilEventObject *self, id source);

FOUNDATION_EXPORT JavaUtilEventObject *new_JavaUtilEventObject_initWithId_(id source) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilEventObject)

#endif // _JavaUtilEventObject_H_
