//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/InvalidPropertiesFormatException.java
//

#ifndef _JavaUtilInvalidPropertiesFormatException_H_
#define _JavaUtilInvalidPropertiesFormatException_H_

#include "J2ObjC_header.h"
#include "java/io/IOException.h"

@class JavaLangThrowable;

@interface JavaUtilInvalidPropertiesFormatException : JavaIoIOException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)m;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)c;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilInvalidPropertiesFormatException)

FOUNDATION_EXPORT void JavaUtilInvalidPropertiesFormatException_initWithNSString_(JavaUtilInvalidPropertiesFormatException *self, NSString *m);

FOUNDATION_EXPORT JavaUtilInvalidPropertiesFormatException *new_JavaUtilInvalidPropertiesFormatException_initWithNSString_(NSString *m) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilInvalidPropertiesFormatException_initWithJavaLangThrowable_(JavaUtilInvalidPropertiesFormatException *self, JavaLangThrowable *c);

FOUNDATION_EXPORT JavaUtilInvalidPropertiesFormatException *new_JavaUtilInvalidPropertiesFormatException_initWithJavaLangThrowable_(JavaLangThrowable *c) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilInvalidPropertiesFormatException)

#endif // _JavaUtilInvalidPropertiesFormatException_H_
