//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/Random.java
//

#ifndef _JavaUtilRandom_H_
#define _JavaUtilRandom_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSByteArray;

@interface JavaUtilRandom : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)seed;

- (jboolean)nextBoolean;

- (void)nextBytesWithByteArray:(IOSByteArray *)buf;

- (jdouble)nextDouble;

- (jfloat)nextFloat;

- (jdouble)nextGaussian;

- (jint)nextInt;

- (jint)nextIntWithInt:(jint)n;

- (jlong)nextLong;

- (void)setSeedWithLong:(jlong)seed;

#pragma mark Protected

- (jint)nextWithInt:(jint)bits;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilRandom)

FOUNDATION_EXPORT void JavaUtilRandom_init(JavaUtilRandom *self);

FOUNDATION_EXPORT JavaUtilRandom *new_JavaUtilRandom_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilRandom_initWithLong_(JavaUtilRandom *self, jlong seed);

FOUNDATION_EXPORT JavaUtilRandom *new_JavaUtilRandom_initWithLong_(jlong seed) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilRandom)

#endif // _JavaUtilRandom_H_
