//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/ResourceBundle.java
//

#ifndef _JavaUtilResourceBundle_H_
#define _JavaUtilResourceBundle_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaLangClassLoader;
@class JavaUtilLocale;
@class JavaUtilResourceBundle_Control;
@protocol JavaUtilEnumeration;
@protocol JavaUtilList;
@protocol JavaUtilSet;

@interface JavaUtilResourceBundle : NSObject {
 @public
  JavaUtilResourceBundle *parent_;
}

#pragma mark Public

- (instancetype)init;

+ (void)clearCache;

+ (void)clearCacheWithJavaLangClassLoader:(JavaLangClassLoader *)loader;

- (jboolean)containsKeyWithNSString:(NSString *)key;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)bundleName;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)baseName
               withJavaUtilResourceBundle_Control:(JavaUtilResourceBundle_Control *)control;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)bundleName
                               withJavaUtilLocale:(JavaUtilLocale *)locale;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)bundleName
                               withJavaUtilLocale:(JavaUtilLocale *)locale
                          withJavaLangClassLoader:(JavaLangClassLoader *)loader;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)baseName
                               withJavaUtilLocale:(JavaUtilLocale *)targetLocale
                          withJavaLangClassLoader:(JavaLangClassLoader *)loader
               withJavaUtilResourceBundle_Control:(JavaUtilResourceBundle_Control *)control;

+ (JavaUtilResourceBundle *)getBundleWithNSString:(NSString *)baseName
                               withJavaUtilLocale:(JavaUtilLocale *)targetLocale
               withJavaUtilResourceBundle_Control:(JavaUtilResourceBundle_Control *)control;

- (id<JavaUtilEnumeration>)getKeys;

- (JavaUtilLocale *)getLocale;

- (id)getObjectWithNSString:(NSString *)key;

- (NSString *)getStringWithNSString:(NSString *)key;

- (IOSObjectArray *)getStringArrayWithNSString:(NSString *)key;

- (id<JavaUtilSet>)keySet;

#pragma mark Protected

- (id)handleGetObjectWithNSString:(NSString *)key;

- (id<JavaUtilSet>)handleKeySet;

- (void)setParentWithJavaUtilResourceBundle:(JavaUtilResourceBundle *)bundle;

@end

J2OBJC_STATIC_INIT(JavaUtilResourceBundle)

J2OBJC_FIELD_SETTER(JavaUtilResourceBundle, parent_, JavaUtilResourceBundle *)

FOUNDATION_EXPORT void JavaUtilResourceBundle_init(JavaUtilResourceBundle *self);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_(NSString *bundleName);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_withJavaUtilLocale_(NSString *bundleName, JavaUtilLocale *locale);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_withJavaUtilLocale_withJavaLangClassLoader_(NSString *bundleName, JavaUtilLocale *locale, JavaLangClassLoader *loader);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_withJavaUtilResourceBundle_Control_(NSString *baseName, JavaUtilResourceBundle_Control *control);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_withJavaUtilLocale_withJavaUtilResourceBundle_Control_(NSString *baseName, JavaUtilLocale *targetLocale, JavaUtilResourceBundle_Control *control);

FOUNDATION_EXPORT JavaUtilResourceBundle *JavaUtilResourceBundle_getBundleWithNSString_withJavaUtilLocale_withJavaLangClassLoader_withJavaUtilResourceBundle_Control_(NSString *baseName, JavaUtilLocale *targetLocale, JavaLangClassLoader *loader, JavaUtilResourceBundle_Control *control);

FOUNDATION_EXPORT void JavaUtilResourceBundle_clearCache();

FOUNDATION_EXPORT void JavaUtilResourceBundle_clearCacheWithJavaLangClassLoader_(JavaLangClassLoader *loader);

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilResourceBundle)

@interface JavaUtilResourceBundle_MissingBundle : JavaUtilResourceBundle

#pragma mark Public

- (id<JavaUtilEnumeration>)getKeys;

- (id)handleGetObjectWithNSString:(NSString *)name;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilResourceBundle_MissingBundle)

FOUNDATION_EXPORT void JavaUtilResourceBundle_MissingBundle_init(JavaUtilResourceBundle_MissingBundle *self);

FOUNDATION_EXPORT JavaUtilResourceBundle_MissingBundle *new_JavaUtilResourceBundle_MissingBundle_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilResourceBundle_MissingBundle)

#define JavaUtilResourceBundle_Control_TTL_DONT_CACHE -1LL
#define JavaUtilResourceBundle_Control_TTL_NO_EXPIRATION_CONTROL -2LL

@interface JavaUtilResourceBundle_Control : NSObject {
 @public
  id<JavaUtilList> format_;
}

#pragma mark Public

- (id<JavaUtilList>)getCandidateLocalesWithNSString:(NSString *)baseName
                                 withJavaUtilLocale:(JavaUtilLocale *)locale;

+ (JavaUtilResourceBundle_Control *)getControlWithJavaUtilList:(id<JavaUtilList>)formats;

- (JavaUtilLocale *)getFallbackLocaleWithNSString:(NSString *)baseName
                               withJavaUtilLocale:(JavaUtilLocale *)locale;

- (id<JavaUtilList>)getFormatsWithNSString:(NSString *)baseName;

+ (JavaUtilResourceBundle_Control *)getNoFallbackControlWithJavaUtilList:(id<JavaUtilList>)formats;

- (jlong)getTimeToLiveWithNSString:(NSString *)baseName
                withJavaUtilLocale:(JavaUtilLocale *)locale;

- (jboolean)needsReloadWithNSString:(NSString *)baseName
                 withJavaUtilLocale:(JavaUtilLocale *)locale
                       withNSString:(NSString *)format
            withJavaLangClassLoader:(JavaLangClassLoader *)loader
         withJavaUtilResourceBundle:(JavaUtilResourceBundle *)bundle
                           withLong:(jlong)loadTime;

- (JavaUtilResourceBundle *)newBundleWithNSString:(NSString *)baseName
                               withJavaUtilLocale:(JavaUtilLocale *)locale
                                     withNSString:(NSString *)format
                          withJavaLangClassLoader:(JavaLangClassLoader *)loader
                                      withBoolean:(jboolean)reload OBJC_METHOD_FAMILY_NONE;

- (NSString *)toBundleNameWithNSString:(NSString *)baseName
                    withJavaUtilLocale:(JavaUtilLocale *)locale;

- (NSString *)toResourceNameWithNSString:(NSString *)bundleName
                            withNSString:(NSString *)suffix;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(JavaUtilResourceBundle_Control)

J2OBJC_FIELD_SETTER(JavaUtilResourceBundle_Control, format_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_listDefault_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, listDefault_, id<JavaUtilList>)
J2OBJC_STATIC_FIELD_SETTER(JavaUtilResourceBundle_Control, listDefault_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_listClass_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, listClass_, id<JavaUtilList>)
J2OBJC_STATIC_FIELD_SETTER(JavaUtilResourceBundle_Control, listClass_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_listProperties_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, listProperties_, id<JavaUtilList>)
J2OBJC_STATIC_FIELD_SETTER(JavaUtilResourceBundle_Control, listProperties_, id<JavaUtilList>)

FOUNDATION_EXPORT NSString *JavaUtilResourceBundle_Control_JAVACLASS_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, JAVACLASS_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(JavaUtilResourceBundle_Control, JAVACLASS_, NSString *)

FOUNDATION_EXPORT NSString *JavaUtilResourceBundle_Control_JAVAPROPERTIES_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, JAVAPROPERTIES_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(JavaUtilResourceBundle_Control, JAVAPROPERTIES_, NSString *)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_FORMAT_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, FORMAT_DEFAULT_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_FORMAT_CLASS_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, FORMAT_CLASS_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilList> JavaUtilResourceBundle_Control_FORMAT_PROPERTIES_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, FORMAT_PROPERTIES_, id<JavaUtilList>)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, TTL_DONT_CACHE, jlong)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilResourceBundle_Control, TTL_NO_EXPIRATION_CONTROL, jlong)

FOUNDATION_EXPORT void JavaUtilResourceBundle_Control_init(JavaUtilResourceBundle_Control *self);

FOUNDATION_EXPORT JavaUtilResourceBundle_Control *new_JavaUtilResourceBundle_Control_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaUtilResourceBundle_Control *JavaUtilResourceBundle_Control_getControlWithJavaUtilList_(id<JavaUtilList> formats);

FOUNDATION_EXPORT JavaUtilResourceBundle_Control *JavaUtilResourceBundle_Control_getNoFallbackControlWithJavaUtilList_(id<JavaUtilList> formats);

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilResourceBundle_Control)

#endif // _JavaUtilResourceBundle_H_
