//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/crypto/SecretKey.java
//

#ifndef _JavaxCryptoSecretKey_H_
#define _JavaxCryptoSecretKey_H_

#include "J2ObjC_header.h"
#include "java/security/Key.h"

#define JavaxCryptoSecretKey_serialVersionUID -4795878709595146952LL

@protocol JavaxCryptoSecretKey < JavaSecurityKey, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoSecretKey)

J2OBJC_STATIC_FIELD_GETTER(JavaxCryptoSecretKey, serialVersionUID, jlong)

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoSecretKey)

#endif // _JavaxCryptoSecretKey_H_
