//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/sun/misc/Unsafe.java
//

#ifndef _SunMiscUnsafe_H_
#define _SunMiscUnsafe_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class JavaLangReflectField;

@interface SunMiscUnsafe : NSObject

#pragma mark Public

- (id)allocateInstanceWithIOSClass:(IOSClass *)c OBJC_METHOD_FAMILY_NONE;

- (jint)arrayBaseOffsetWithIOSClass:(IOSClass *)clazz;

- (jint)arrayIndexScaleWithIOSClass:(IOSClass *)clazz;

- (jboolean)compareAndSwapArrayObjectWithId:(id)array
                                    withInt:(jint)index
                                     withId:(id)expectedValue
                                     withId:(id)newValue;

- (jboolean)compareAndSwapIntWithId:(id)obj
                           withLong:(jlong)offset
                            withInt:(jint)expectedValue
                            withInt:(jint)newValue;

- (jboolean)compareAndSwapLongWithId:(id)obj
                            withLong:(jlong)offset
                            withLong:(jlong)expectedValue
                            withLong:(jlong)newValue;

- (jboolean)compareAndSwapObjectWithId:(id)obj
                              withLong:(jlong)offset
                                withId:(id)expectedValue
                                withId:(id)newValue;

- (id)getArrayObjectWithId:(id)array
                   withInt:(jint)index;

- (id)getArrayObjectVolatileWithId:(id)array
                           withInt:(jint)index;

- (jint)getIntWithId:(id)obj
            withLong:(jlong)offset;

- (jint)getIntVolatileWithId:(id)obj
                    withLong:(jlong)offset;

- (jlong)getLongWithId:(id)obj
              withLong:(jlong)offset;

- (jlong)getLongVolatileWithId:(id)obj
                      withLong:(jlong)offset;

- (id)getObjectWithId:(id)obj
             withLong:(jlong)offset;

- (id)getObjectVolatileWithId:(id)obj
                     withLong:(jlong)offset;

+ (SunMiscUnsafe *)getUnsafe;

- (jlong)objectFieldOffsetWithJavaLangReflectField:(JavaLangReflectField *)field;

- (void)parkWithBoolean:(jboolean)absolute
               withLong:(jlong)time;

- (void)putArrayObjectWithId:(id)array
                     withInt:(jint)index
                      withId:(id)newValue;

- (void)putArrayObjectVolatileWithId:(id)array
                             withInt:(jint)index
                              withId:(id)newValue;

- (void)putArrayOrderedObjectWithId:(id)array
                            withInt:(jint)index
                             withId:(id)newValue;

- (void)putIntWithId:(id)obj
            withLong:(jlong)offset
             withInt:(jint)newValue;

- (void)putIntVolatileWithId:(id)obj
                    withLong:(jlong)offset
                     withInt:(jint)newValue;

- (void)putLongWithId:(id)obj
             withLong:(jlong)offset
             withLong:(jlong)newValue;

- (void)putLongVolatileWithId:(id)obj
                     withLong:(jlong)offset
                     withLong:(jlong)newValue;

- (void)putObjectWithId:(id)obj
               withLong:(jlong)offset
                 withId:(id)newValue;

- (void)putObjectVolatileWithId:(id)obj
                       withLong:(jlong)offset
                         withId:(id)newValue;

- (void)putOrderedIntWithId:(id)obj
                   withLong:(jlong)offset
                    withInt:(jint)newValue;

- (void)putOrderedLongWithId:(id)obj
                    withLong:(jlong)offset
                    withLong:(jlong)newValue;

- (void)putOrderedObjectWithId:(id)obj
                      withLong:(jlong)offset
                        withId:(id)newValue;

- (void)unparkWithId:(id)obj;

@end

J2OBJC_STATIC_INIT(SunMiscUnsafe)

FOUNDATION_EXPORT SunMiscUnsafe *SunMiscUnsafe_getUnsafe();

J2OBJC_TYPE_LITERAL_HEADER(SunMiscUnsafe)

#endif // _SunMiscUnsafe_H_
