//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/LayerManager.java
//

#ifndef _OrgMapsforgeMapLayerLayerManager_H_
#define _OrgMapsforgeMapLayerLayerManager_H_

#include "J2ObjC_header.h"
#include "org/mapsforge/map/layer/Redrawer.h"
#include "org/mapsforge/map/util/PausableThread.h"

@class OrgMapsforgeMapLayerLayers;
@class OrgMapsforgeMapModelMapViewPosition;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeMapViewMapView;

@interface OrgMapsforgeMapLayerLayerManager : OrgMapsforgeMapUtilPausableThread < OrgMapsforgeMapLayerRedrawer >

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapViewMapView:(id<OrgMapsforgeMapViewMapView>)mapView
           withOrgMapsforgeMapModelMapViewPosition:(OrgMapsforgeMapModelMapViewPosition *)mapViewPosition
        withOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory;

- (OrgMapsforgeMapLayerLayers *)getLayers;

- (void)redrawLayers;

#pragma mark Protected

- (void)afterRun;

- (void)doWork;

- (OrgMapsforgeMapUtilPausableThread_ThreadPriorityEnum *)getThreadPriority;

- (jboolean)hasWork;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerLayerManager)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerLayerManager_initWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeCoreGraphicsGraphicFactory_(OrgMapsforgeMapLayerLayerManager *self, id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory);

FOUNDATION_EXPORT OrgMapsforgeMapLayerLayerManager *new_OrgMapsforgeMapLayerLayerManager_initWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelMapViewPosition_withOrgMapsforgeCoreGraphicsGraphicFactory_(id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelMapViewPosition *mapViewPosition, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerLayerManager)

#endif // _OrgMapsforgeMapLayerLayerManager_H_
