//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/io/StructPollfd.java
//

#ifndef _LibcoreIoStructPollfd_H_
#define _LibcoreIoStructPollfd_H_

#include "J2ObjC_header.h"

@class JavaIoFileDescriptor;

@interface LibcoreIoStructPollfd : NSObject {
 @public
  JavaIoFileDescriptor *fd_;
  jshort events_;
  jshort revents_;
  id userData_;
}

#pragma mark Public

- (instancetype)init;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(LibcoreIoStructPollfd)

J2OBJC_FIELD_SETTER(LibcoreIoStructPollfd, fd_, JavaIoFileDescriptor *)
J2OBJC_FIELD_SETTER(LibcoreIoStructPollfd, userData_, id)

FOUNDATION_EXPORT void LibcoreIoStructPollfd_init(LibcoreIoStructPollfd *self);

FOUNDATION_EXPORT LibcoreIoStructPollfd *new_LibcoreIoStructPollfd_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(LibcoreIoStructPollfd)

#endif // _LibcoreIoStructPollfd_H_
