//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/io/StructFlock.java
//

#ifndef _LibcoreIoStructFlock_H_
#define _LibcoreIoStructFlock_H_

#include "J2ObjC_header.h"

@interface LibcoreIoStructFlock : NSObject {
 @public
  jshort l_type_;
  jshort l_whence_;
  jlong l_start_;
  jlong l_len_;
  jint l_pid_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(LibcoreIoStructFlock)

FOUNDATION_EXPORT void LibcoreIoStructFlock_init(LibcoreIoStructFlock *self);

FOUNDATION_EXPORT LibcoreIoStructFlock *new_LibcoreIoStructFlock_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(LibcoreIoStructFlock)

#endif // _LibcoreIoStructFlock_H_
