//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/testing/mockito/build_result/java/org/mockito/listeners/InvocationListener.java
//

#ifndef _OrgMockitoListenersInvocationListener_H_
#define _OrgMockitoListenersInvocationListener_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoListenersMethodInvocationReport;

@protocol OrgMockitoListenersInvocationListener < NSObject, JavaObject >

- (void)reportInvocationWithOrgMockitoListenersMethodInvocationReport:(id<OrgMockitoListenersMethodInvocationReport>)methodInvocationReport;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoListenersInvocationListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoListenersInvocationListener)

#endif // _OrgMockitoListenersInvocationListener_H_
