//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/testing/mockito/build_result/java/org/mockito/internal/matchers/ContainsExtraTypeInformation.java
//

#ifndef _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_
#define _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@protocol OrgHamcrestSelfDescribing;

@protocol OrgMockitoInternalMatchersContainsExtraTypeInformation < JavaIoSerializable, NSObject, JavaObject >

- (id<OrgHamcrestSelfDescribing>)withExtraTypeInfo;

- (jboolean)typeMatchesWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalMatchersContainsExtraTypeInformation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalMatchersContainsExtraTypeInformation)

#endif // _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_
