//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/inject/javax_inject/build_result/java/javax/inject/Inject.java
//

#ifndef _JavaxInjectInject_H_
#define _JavaxInjectInject_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxInjectInject < JavaLangAnnotationAnnotation >

@end

@interface JavaxInjectInject : NSObject < JavaxInjectInject >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxInjectInject)

J2OBJC_TYPE_LITERAL_HEADER(JavaxInjectInject)

#endif // _JavaxInjectInject_H_
