//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/ReadOnlyBufferException.java
//

#ifndef _JavaNioReadOnlyBufferException_H_
#define _JavaNioReadOnlyBufferException_H_

#include "J2ObjC_header.h"
#include "java/lang/UnsupportedOperationException.h"

@interface JavaNioReadOnlyBufferException : JavaLangUnsupportedOperationException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioReadOnlyBufferException)

FOUNDATION_EXPORT void JavaNioReadOnlyBufferException_init(JavaNioReadOnlyBufferException *self);

FOUNDATION_EXPORT JavaNioReadOnlyBufferException *new_JavaNioReadOnlyBufferException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioReadOnlyBufferException)

#endif // _JavaNioReadOnlyBufferException_H_
