//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/Inflater.java
//

#ifndef _JavaUtilZipInflater_H_
#define _JavaUtilZipInflater_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@class JavaIoFileDescriptor;

@interface JavaUtilZipInflater : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)noHeader;

- (void)end;

- (jboolean)finished;

- (jint)getAdler;

- (jlong)getBytesRead;

- (jlong)getBytesWritten;

- (jint)getRemaining;

- (jint)getTotalIn;

- (jint)getTotalOut;

- (jint)inflateWithByteArray:(IOSByteArray *)buf;

- (jint)inflateWithByteArray:(IOSByteArray *)buf
                     withInt:(jint)offset
                     withInt:(jint)byteCount;

- (jboolean)needsDictionary;

- (jboolean)needsInput;

- (void)reset;

- (void)setDictionaryWithByteArray:(IOSByteArray *)dictionary;

- (void)setDictionaryWithByteArray:(IOSByteArray *)dictionary
                           withInt:(jint)offset
                           withInt:(jint)byteCount;

- (void)setInputWithByteArray:(IOSByteArray *)buf;

- (void)setInputWithByteArray:(IOSByteArray *)buf
                      withInt:(jint)offset
                      withInt:(jint)byteCount;

#pragma mark Protected

- (void)dealloc;

#pragma mark Package-Private

- (jint)getCurrentOffset;

- (jint)setFileInputWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd
                                    withLong:(jlong)offset
                                     withInt:(jint)byteCount;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilZipInflater)

FOUNDATION_EXPORT void JavaUtilZipInflater_init(JavaUtilZipInflater *self);

FOUNDATION_EXPORT JavaUtilZipInflater *new_JavaUtilZipInflater_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilZipInflater_initWithBoolean_(JavaUtilZipInflater *self, jboolean noHeader);

FOUNDATION_EXPORT JavaUtilZipInflater *new_JavaUtilZipInflater_initWithBoolean_(jboolean noHeader) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilZipInflater)

#endif // _JavaUtilZipInflater_H_
