//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/ZipFile.java
//

#ifndef _JavaUtilZipZipFile_H_
#define _JavaUtilZipZipFile_H_

#include "J2ObjC_header.h"
#include "java/io/Closeable.h"
#include "java/io/InputStream.h"
#include "java/util/zip/InflaterInputStream.h"
#include "java/util/zip/ZipConstants.h"

@class IOSByteArray;
@class JavaIoFile;
@class JavaIoRandomAccessFile;
@class JavaUtilZipInflater;
@class JavaUtilZipZipEntry;
@protocol JavaUtilEnumeration;

#define JavaUtilZipZipFile_GPBF_ENCRYPTED_FLAG 1
#define JavaUtilZipZipFile_GPBF_DATA_DESCRIPTOR_FLAG 8
#define JavaUtilZipZipFile_GPBF_UTF8_FLAG 2048
#define JavaUtilZipZipFile_GPBF_UNSUPPORTED_MASK 1
#define JavaUtilZipZipFile_OPEN_READ 1
#define JavaUtilZipZipFile_OPEN_DELETE 4

@interface JavaUtilZipZipFile : NSObject < JavaIoCloseable, JavaUtilZipZipConstants >

#pragma mark Public

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file
                           withInt:(jint)mode;

- (instancetype)initWithNSString:(NSString *)name;

- (void)close;

- (id<JavaUtilEnumeration>)entries;

- (NSString *)getComment;

- (JavaUtilZipZipEntry *)getEntryWithNSString:(NSString *)entryName;

- (JavaIoInputStream *)getInputStreamWithJavaUtilZipZipEntry:(JavaUtilZipZipEntry *)entry_;

- (NSString *)getName;

- (jint)size;

#pragma mark Protected

- (void)dealloc;

#pragma mark Package-Private

+ (void)throwZipExceptionWithNSString:(NSString *)msg
                              withInt:(jint)magic;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilZipZipFile)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, GPBF_ENCRYPTED_FLAG, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, GPBF_DATA_DESCRIPTOR_FLAG, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, GPBF_UTF8_FLAG, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, GPBF_UNSUPPORTED_MASK, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, OPEN_READ, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilZipZipFile, OPEN_DELETE, jint)

FOUNDATION_EXPORT void JavaUtilZipZipFile_initWithJavaIoFile_(JavaUtilZipZipFile *self, JavaIoFile *file);

FOUNDATION_EXPORT JavaUtilZipZipFile *new_JavaUtilZipZipFile_initWithJavaIoFile_(JavaIoFile *file) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilZipZipFile_initWithNSString_(JavaUtilZipZipFile *self, NSString *name);

FOUNDATION_EXPORT JavaUtilZipZipFile *new_JavaUtilZipZipFile_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilZipZipFile_initWithJavaIoFile_withInt_(JavaUtilZipZipFile *self, JavaIoFile *file, jint mode);

FOUNDATION_EXPORT JavaUtilZipZipFile *new_JavaUtilZipZipFile_initWithJavaIoFile_withInt_(JavaIoFile *file, jint mode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilZipZipFile_throwZipExceptionWithNSString_withInt_(NSString *msg, jint magic);

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilZipZipFile)

@interface JavaUtilZipZipFile_RAFStream : JavaIoInputStream

#pragma mark Public

- (instancetype)initWithJavaIoRandomAccessFile:(JavaIoRandomAccessFile *)raf
                                      withLong:(jlong)initialOffset;

- (instancetype)initWithJavaIoRandomAccessFile:(JavaIoRandomAccessFile *)raf
                                      withLong:(jlong)initialOffset
                                      withLong:(jlong)endOffset;

- (jint)available;

- (jint)fillWithJavaUtilZipInflater:(JavaUtilZipInflater *)inflater
                            withInt:(jint)nativeEndBufSize;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

- (jlong)skipWithLong:(jlong)byteCount;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilZipZipFile_RAFStream)

FOUNDATION_EXPORT void JavaUtilZipZipFile_RAFStream_initWithJavaIoRandomAccessFile_withLong_withLong_(JavaUtilZipZipFile_RAFStream *self, JavaIoRandomAccessFile *raf, jlong initialOffset, jlong endOffset);

FOUNDATION_EXPORT JavaUtilZipZipFile_RAFStream *new_JavaUtilZipZipFile_RAFStream_initWithJavaIoRandomAccessFile_withLong_withLong_(JavaIoRandomAccessFile *raf, jlong initialOffset, jlong endOffset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilZipZipFile_RAFStream_initWithJavaIoRandomAccessFile_withLong_(JavaUtilZipZipFile_RAFStream *self, JavaIoRandomAccessFile *raf, jlong initialOffset);

FOUNDATION_EXPORT JavaUtilZipZipFile_RAFStream *new_JavaUtilZipZipFile_RAFStream_initWithJavaIoRandomAccessFile_withLong_(JavaIoRandomAccessFile *raf, jlong initialOffset) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilZipZipFile_RAFStream)

@interface JavaUtilZipZipFile_ZipInflaterInputStream : JavaUtilZipInflaterInputStream

#pragma mark Public

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)is
                  withJavaUtilZipInflater:(JavaUtilZipInflater *)inf
                                  withInt:(jint)bsize
                  withJavaUtilZipZipEntry:(JavaUtilZipZipEntry *)entry_;

- (jint)available;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilZipZipFile_ZipInflaterInputStream)

FOUNDATION_EXPORT void JavaUtilZipZipFile_ZipInflaterInputStream_initWithJavaIoInputStream_withJavaUtilZipInflater_withInt_withJavaUtilZipZipEntry_(JavaUtilZipZipFile_ZipInflaterInputStream *self, JavaIoInputStream *is, JavaUtilZipInflater *inf, jint bsize, JavaUtilZipZipEntry *entry_);

FOUNDATION_EXPORT JavaUtilZipZipFile_ZipInflaterInputStream *new_JavaUtilZipZipFile_ZipInflaterInputStream_initWithJavaIoInputStream_withJavaUtilZipInflater_withInt_withJavaUtilZipZipEntry_(JavaIoInputStream *is, JavaUtilZipInflater *inf, jint bsize, JavaUtilZipZipEntry *entry_) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilZipZipFile_ZipInflaterInputStream)

#endif // _JavaUtilZipZipFile_H_
