//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/Provider.java
//

#ifndef _JavaSecurityProvider_H_
#define _JavaSecurityProvider_H_

#include "J2ObjC_header.h"
#include "java/util/Properties.h"

@class JavaIoInputStream;
@class JavaSecurityProvider_Service;
@protocol JavaUtilCollection;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface JavaSecurityProvider : JavaUtilProperties

#pragma mark Public

- (void)clear;

- (id<JavaUtilSet>)entrySet;

- (NSString *)getInfo;

- (NSString *)getName;

- (JavaSecurityProvider_Service *)getServiceWithNSString:(NSString *)type
                                            withNSString:(NSString *)algorithm;

- (id<JavaUtilSet>)getServices;

- (jdouble)getVersion;

- (id<JavaUtilSet>)keySet;

- (void)load__WithJavaIoInputStream:(JavaIoInputStream *)inStream;

- (id)putWithId:(id)key
         withId:(id)value;

- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)t;

- (id)removeWithId:(id)key;

- (NSString *)description;

- (id<JavaUtilCollection>)values;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)name
                      withDouble:(jdouble)version_
                    withNSString:(NSString *)info;

- (void)putServiceWithJavaSecurityProvider_Service:(JavaSecurityProvider_Service *)s;

- (void)removeServiceWithJavaSecurityProvider_Service:(JavaSecurityProvider_Service *)s;

#pragma mark Package-Private

- (jint)getProviderNumber;

- (JavaSecurityProvider_Service *)getServiceWithNSString:(NSString *)type;

- (jboolean)implementsAlgWithNSString:(NSString *)serv
                         withNSString:(NSString *)alg
                         withNSString:(NSString *)attribute
                         withNSString:(NSString *)val;

- (void)setProviderNumberWithInt:(jint)n;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityProvider)

FOUNDATION_EXPORT void JavaSecurityProvider_initWithNSString_withDouble_withNSString_(JavaSecurityProvider *self, NSString *name, jdouble version_, NSString *info);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityProvider)

@interface JavaSecurityProvider_Service : NSObject

#pragma mark Public

- (instancetype)initWithJavaSecurityProvider:(JavaSecurityProvider *)provider
                                withNSString:(NSString *)type
                                withNSString:(NSString *)algorithm
                                withNSString:(NSString *)className_
                            withJavaUtilList:(id<JavaUtilList>)aliases
                             withJavaUtilMap:(id<JavaUtilMap>)attributes;

- (NSString *)getAlgorithm;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (NSString *)getClassName;

- (JavaSecurityProvider *)getProvider;

- (NSString *)getType;

- (id)newInstanceWithId:(id)constructorParameter OBJC_METHOD_FAMILY_NONE;

- (jboolean)supportsParameterWithId:(id)parameter;

- (NSString *)description;

#pragma mark Package-Private

- (void)addAliasWithNSString:(NSString *)alias;

- (id<JavaUtilList>)getAliases;

- (void)putAttributeWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityProvider_Service)

FOUNDATION_EXPORT void JavaSecurityProvider_Service_initWithJavaSecurityProvider_withNSString_withNSString_withNSString_withJavaUtilList_withJavaUtilMap_(JavaSecurityProvider_Service *self, JavaSecurityProvider *provider, NSString *type, NSString *algorithm, NSString *className_, id<JavaUtilList> aliases, id<JavaUtilMap> attributes);

FOUNDATION_EXPORT JavaSecurityProvider_Service *new_JavaSecurityProvider_Service_initWithJavaSecurityProvider_withNSString_withNSString_withNSString_withJavaUtilList_withJavaUtilMap_(JavaSecurityProvider *provider, NSString *type, NSString *algorithm, NSString *className_, id<JavaUtilList> aliases, id<JavaUtilMap> attributes) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityProvider_Service)

#endif // _JavaSecurityProvider_H_
