//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/SecureRandomSpi.java
//

#ifndef _JavaSecuritySecureRandomSpi_H_
#define _JavaSecuritySecureRandomSpi_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSByteArray;

@interface JavaSecuritySecureRandomSpi : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (IOSByteArray *)engineGenerateSeedWithInt:(jint)numBytes;

- (void)engineNextBytesWithByteArray:(IOSByteArray *)bytes;

- (void)engineSetSeedWithByteArray:(IOSByteArray *)seed;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySecureRandomSpi)

FOUNDATION_EXPORT void JavaSecuritySecureRandomSpi_init(JavaSecuritySecureRandomSpi *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySecureRandomSpi)

#endif // _JavaSecuritySecureRandomSpi_H_
