//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/base/Enums.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonBaseEnums_INCLUDE_ALL")
#if ComGoogleCommonBaseEnums_RESTRICT
#define ComGoogleCommonBaseEnums_INCLUDE_ALL 0
#else
#define ComGoogleCommonBaseEnums_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonBaseEnums_RESTRICT

#if !defined (_ComGoogleCommonBaseEnums_) && (ComGoogleCommonBaseEnums_INCLUDE_ALL || ComGoogleCommonBaseEnums_INCLUDE)
#define _ComGoogleCommonBaseEnums_

@class ComGoogleCommonBaseOptional;
@class IOSClass;
@class JavaLangEnum;
@class JavaLangReflectField;
@protocol ComGoogleCommonBaseFunction;

@interface ComGoogleCommonBaseEnums : NSObject

#pragma mark Public

+ (JavaLangReflectField *)getFieldWithJavaLangEnum:(JavaLangEnum *)enumValue;

+ (ComGoogleCommonBaseOptional *)getIfPresentWithIOSClass:(IOSClass *)enumClass
                                             withNSString:(NSString *)value;

+ (id<ComGoogleCommonBaseFunction>)valueOfFunctionWithIOSClass:(IOSClass *)enumClass;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseEnums)

FOUNDATION_EXPORT JavaLangReflectField *ComGoogleCommonBaseEnums_getFieldWithJavaLangEnum_(JavaLangEnum *enumValue);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonBaseEnums_valueOfFunctionWithIOSClass_(IOSClass *enumClass);

FOUNDATION_EXPORT ComGoogleCommonBaseOptional *ComGoogleCommonBaseEnums_getIfPresentWithIOSClass_withNSString_(IOSClass *enumClass, NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseEnums)

#endif

#if !defined (_ComGoogleCommonBaseEnums_ValueOfFunction_) && (ComGoogleCommonBaseEnums_INCLUDE_ALL || ComGoogleCommonBaseEnums_ValueOfFunction_INCLUDE)
#define _ComGoogleCommonBaseEnums_ValueOfFunction_

#endif
#pragma pop_macro("ComGoogleCommonBaseEnums_INCLUDE_ALL")
