//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/XmlRenderTheme.java
//

#ifndef _OrgMapsforgeMapRenderthemeXmlRenderTheme_H_
#define _OrgMapsforgeMapRenderthemeXmlRenderTheme_H_

#include "J2ObjC_header.h"

@class JavaIoInputStream;
@protocol OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback;

@protocol OrgMapsforgeMapRenderthemeXmlRenderTheme < NSObject, JavaObject >

- (id<OrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback>)getMenuCallback;

- (NSString *)getRelativePathPrefix;

- (JavaIoInputStream *)getRenderThemeAsStream;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapRenderthemeXmlRenderTheme)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapRenderthemeXmlRenderTheme)

#endif // _OrgMapsforgeMapRenderthemeXmlRenderTheme_H_
