//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/layer/renderer/CircleContainer.java
//

#ifndef _OrgMapsforgeMapLayerRendererCircleContainer_H_
#define _OrgMapsforgeMapLayerRendererCircleContainer_H_

#include "J2ObjC_header.h"
#include "org/mapsforge/map/layer/renderer/ShapeContainer.h"

@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeMapLayerRendererShapeTypeEnum;

@interface OrgMapsforgeMapLayerRendererCircleContainer : NSObject < OrgMapsforgeMapLayerRendererShapeContainer > {
 @public
  OrgMapsforgeCoreModelPoint *point_;
  jfloat radius_;
}

#pragma mark Public

- (OrgMapsforgeMapLayerRendererShapeTypeEnum *)getShapeType;

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point
                                         withFloat:(jfloat)radius;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapLayerRendererCircleContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapLayerRendererCircleContainer, point_, OrgMapsforgeCoreModelPoint *)

FOUNDATION_EXPORT void OrgMapsforgeMapLayerRendererCircleContainer_initWithOrgMapsforgeCoreModelPoint_withFloat_(OrgMapsforgeMapLayerRendererCircleContainer *self, OrgMapsforgeCoreModelPoint *point, jfloat radius);

FOUNDATION_EXPORT OrgMapsforgeMapLayerRendererCircleContainer *new_OrgMapsforgeMapLayerRendererCircleContainer_initWithOrgMapsforgeCoreModelPoint_withFloat_(OrgMapsforgeCoreModelPoint *point, jfloat radius) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapLayerRendererCircleContainer)

#endif // _OrgMapsforgeMapLayerRendererCircleContainer_H_
