//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/SAXParseException.java
//

#ifndef _OrgXmlSaxSAXParseException_H_
#define _OrgXmlSaxSAXParseException_H_

#include "J2ObjC_header.h"
#include "org/xml/sax/SAXException.h"

@class JavaLangException;
@protocol OrgXmlSaxLocator;

@interface OrgXmlSaxSAXParseException : OrgXmlSaxSAXException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message
            withOrgXmlSaxLocator:(id<OrgXmlSaxLocator>)locator;

- (instancetype)initWithNSString:(NSString *)message
            withOrgXmlSaxLocator:(id<OrgXmlSaxLocator>)locator
           withJavaLangException:(JavaLangException *)e;

- (instancetype)initWithNSString:(NSString *)message
                    withNSString:(NSString *)publicId
                    withNSString:(NSString *)systemId
                         withInt:(jint)lineNumber
                         withInt:(jint)columnNumber;

- (instancetype)initWithNSString:(NSString *)message
                    withNSString:(NSString *)publicId
                    withNSString:(NSString *)systemId
                         withInt:(jint)lineNumber
                         withInt:(jint)columnNumber
           withJavaLangException:(JavaLangException *)e;

- (jint)getColumnNumber;

- (jint)getLineNumber;

- (NSString *)getPublicId;

- (NSString *)getSystemId;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgXmlSaxSAXParseException)

FOUNDATION_EXPORT void OrgXmlSaxSAXParseException_initWithNSString_withOrgXmlSaxLocator_(OrgXmlSaxSAXParseException *self, NSString *message, id<OrgXmlSaxLocator> locator);

FOUNDATION_EXPORT OrgXmlSaxSAXParseException *new_OrgXmlSaxSAXParseException_initWithNSString_withOrgXmlSaxLocator_(NSString *message, id<OrgXmlSaxLocator> locator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgXmlSaxSAXParseException_initWithNSString_withOrgXmlSaxLocator_withJavaLangException_(OrgXmlSaxSAXParseException *self, NSString *message, id<OrgXmlSaxLocator> locator, JavaLangException *e);

FOUNDATION_EXPORT OrgXmlSaxSAXParseException *new_OrgXmlSaxSAXParseException_initWithNSString_withOrgXmlSaxLocator_withJavaLangException_(NSString *message, id<OrgXmlSaxLocator> locator, JavaLangException *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgXmlSaxSAXParseException_initWithNSString_withNSString_withNSString_withInt_withInt_(OrgXmlSaxSAXParseException *self, NSString *message, NSString *publicId, NSString *systemId, jint lineNumber, jint columnNumber);

FOUNDATION_EXPORT OrgXmlSaxSAXParseException *new_OrgXmlSaxSAXParseException_initWithNSString_withNSString_withNSString_withInt_withInt_(NSString *message, NSString *publicId, NSString *systemId, jint lineNumber, jint columnNumber) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgXmlSaxSAXParseException_initWithNSString_withNSString_withNSString_withInt_withInt_withJavaLangException_(OrgXmlSaxSAXParseException *self, NSString *message, NSString *publicId, NSString *systemId, jint lineNumber, jint columnNumber, JavaLangException *e);

FOUNDATION_EXPORT OrgXmlSaxSAXParseException *new_OrgXmlSaxSAXParseException_initWithNSString_withNSString_withNSString_withInt_withInt_withJavaLangException_(NSString *message, NSString *publicId, NSString *systemId, jint lineNumber, jint columnNumber, JavaLangException *e) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgXmlSaxSAXParseException)

#endif // _OrgXmlSaxSAXParseException_H_
