//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/xml/dom/NodeImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomNodeImpl_H_
#define _OrgApacheHarmonyXmlDomNodeImpl_H_

#include "J2ObjC_header.h"
#include "org/w3c/dom/Node.h"

@class JavaLangStringBuilder;
@class OrgApacheHarmonyXmlDomDocumentImpl;
@protocol OrgW3cDomDocument;
@protocol OrgW3cDomNamedNodeMap;
@protocol OrgW3cDomNodeList;
@protocol OrgW3cDomTypeInfo;
@protocol OrgW3cDomUserDataHandler;

@interface OrgApacheHarmonyXmlDomNodeImpl : NSObject < OrgW3cDomNode > {
 @public
  OrgApacheHarmonyXmlDomDocumentImpl *document_;
}

#pragma mark Public

- (id<OrgW3cDomNode>)appendChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild;

- (id<OrgW3cDomNode>)cloneNodeWithBoolean:(jboolean)deep;

- (jshort)compareDocumentPositionWithOrgW3cDomNode:(id<OrgW3cDomNode>)other;

- (id<OrgW3cDomNamedNodeMap>)getAttributes;

- (NSString *)getBaseURI;

- (id<OrgW3cDomNodeList>)getChildNodes;

- (id)getFeatureWithNSString:(NSString *)feature
                withNSString:(NSString *)version_;

- (id<OrgW3cDomNode>)getFirstChild;

- (id<OrgW3cDomNode>)getLastChild;

- (NSString *)getLocalName;

- (NSString *)getNamespaceURI;

- (id<OrgW3cDomNode>)getNextSibling;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getNodeValue;

- (id<OrgW3cDomDocument>)getOwnerDocument;

- (id<OrgW3cDomNode>)getParentNode;

- (NSString *)getPrefix;

- (id<OrgW3cDomNode>)getPreviousSibling;

- (NSString *)getTextContent;

- (id)getUserDataWithNSString:(NSString *)key;

- (jboolean)hasAttributes;

- (jboolean)hasChildNodes;

- (id<OrgW3cDomNode>)insertBeforeWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild
                                 withOrgW3cDomNode:(id<OrgW3cDomNode>)refChild;

- (jboolean)isDefaultNamespaceWithNSString:(NSString *)namespaceURI;

- (jboolean)isEqualNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)arg;

- (jboolean)isSameNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)other;

- (jboolean)isSupportedWithNSString:(NSString *)feature
                       withNSString:(NSString *)version_;

- (NSString *)lookupNamespaceURIWithNSString:(NSString *)prefix;

- (NSString *)lookupPrefixWithNSString:(NSString *)namespaceURI;

- (void)normalize;

- (id<OrgW3cDomNode>)removeChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)oldChild;

- (id<OrgW3cDomNode>)replaceChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild
                                 withOrgW3cDomNode:(id<OrgW3cDomNode>)oldChild;

- (void)setNodeValueWithNSString:(NSString *)nodeValue;

- (void)setPrefixWithNSString:(NSString *)prefix;

- (void)setTextContentWithNSString:(NSString *)textContent;

- (id)setUserDataWithNSString:(NSString *)key
                       withId:(id)data
 withOrgW3cDomUserDataHandler:(id<OrgW3cDomUserDataHandler>)handler;

#pragma mark Package-Private

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document;

- (void)getTextContentWithJavaLangStringBuilder:(JavaLangStringBuilder *)buf;

- (jboolean)isPrefixMappedToUriWithNSString:(NSString *)prefix
                               withNSString:(NSString *)uri;

+ (void)setNameWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node
                                     withNSString:(NSString *)name;

+ (void)setNameNSWithOrgApacheHarmonyXmlDomNodeImpl:(OrgApacheHarmonyXmlDomNodeImpl *)node
                                       withNSString:(NSString *)namespaceURI
                                       withNSString:(NSString *)qualifiedName;

+ (NSString *)validatePrefixWithNSString:(NSString *)prefix
                             withBoolean:(jboolean)namespaceAware
                            withNSString:(NSString *)namespaceURI;

@end

J2OBJC_STATIC_INIT(OrgApacheHarmonyXmlDomNodeImpl)

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNodeImpl, document_, OrgApacheHarmonyXmlDomDocumentImpl *)

FOUNDATION_EXPORT id<OrgW3cDomTypeInfo> OrgApacheHarmonyXmlDomNodeImpl_NULL_TYPE_INFO_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyXmlDomNodeImpl, NULL_TYPE_INFO_, id<OrgW3cDomTypeInfo>)

FOUNDATION_EXPORT void OrgApacheHarmonyXmlDomNodeImpl_initWithOrgApacheHarmonyXmlDomDocumentImpl_(OrgApacheHarmonyXmlDomNodeImpl *self, OrgApacheHarmonyXmlDomDocumentImpl *document);

FOUNDATION_EXPORT NSString *OrgApacheHarmonyXmlDomNodeImpl_validatePrefixWithNSString_withBoolean_withNSString_(NSString *prefix, jboolean namespaceAware, NSString *namespaceURI);

FOUNDATION_EXPORT void OrgApacheHarmonyXmlDomNodeImpl_setNameNSWithOrgApacheHarmonyXmlDomNodeImpl_withNSString_withNSString_(OrgApacheHarmonyXmlDomNodeImpl *node, NSString *namespaceURI, NSString *qualifiedName);

FOUNDATION_EXPORT void OrgApacheHarmonyXmlDomNodeImpl_setNameWithOrgApacheHarmonyXmlDomNodeImpl_withNSString_(OrgApacheHarmonyXmlDomNodeImpl *node, NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonyXmlDomNodeImpl)

@interface OrgApacheHarmonyXmlDomNodeImpl_UserData : NSObject {
 @public
  id value_;
  id<OrgW3cDomUserDataHandler> handler_;
}

#pragma mark Package-Private

- (instancetype)initWithId:(id)value
withOrgW3cDomUserDataHandler:(id<OrgW3cDomUserDataHandler>)handler;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonyXmlDomNodeImpl_UserData)

J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNodeImpl_UserData, value_, id)
J2OBJC_FIELD_SETTER(OrgApacheHarmonyXmlDomNodeImpl_UserData, handler_, id<OrgW3cDomUserDataHandler>)

FOUNDATION_EXPORT void OrgApacheHarmonyXmlDomNodeImpl_UserData_initWithId_withOrgW3cDomUserDataHandler_(OrgApacheHarmonyXmlDomNodeImpl_UserData *self, id value, id<OrgW3cDomUserDataHandler> handler);

FOUNDATION_EXPORT OrgApacheHarmonyXmlDomNodeImpl_UserData *new_OrgApacheHarmonyXmlDomNodeImpl_UserData_initWithId_withOrgW3cDomUserDataHandler_(id value, id<OrgW3cDomUserDataHandler> handler) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonyXmlDomNodeImpl_UserData)

#endif // _OrgApacheHarmonyXmlDomNodeImpl_H_
