//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/xpath/XPathFactory.java
//

#ifndef _JavaxXmlXpathXPathFactory_H_
#define _JavaxXmlXpathXPathFactory_H_

#include "J2ObjC_header.h"

@class JavaLangClassLoader;
@protocol JavaxXmlXpathXPath;
@protocol JavaxXmlXpathXPathFunctionResolver;
@protocol JavaxXmlXpathXPathVariableResolver;

@interface JavaxXmlXpathXPathFactory : NSObject

#pragma mark Public

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (jboolean)isObjectModelSupportedWithNSString:(NSString *)objectModel;

+ (JavaxXmlXpathXPathFactory *)newInstance OBJC_METHOD_FAMILY_NONE;

+ (JavaxXmlXpathXPathFactory *)newInstanceWithNSString:(NSString *)uri OBJC_METHOD_FAMILY_NONE;

+ (JavaxXmlXpathXPathFactory *)newInstanceWithNSString:(NSString *)uri
                                          withNSString:(NSString *)factoryClassName
                               withJavaLangClassLoader:(JavaLangClassLoader *)classLoader OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlXpathXPath>)newXPath OBJC_METHOD_FAMILY_NONE;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (void)setXPathFunctionResolverWithJavaxXmlXpathXPathFunctionResolver:(id<JavaxXmlXpathXPathFunctionResolver>)resolver;

- (void)setXPathVariableResolverWithJavaxXmlXpathXPathVariableResolver:(id<JavaxXmlXpathXPathVariableResolver>)resolver;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlXpathXPathFactory)

FOUNDATION_EXPORT NSString *JavaxXmlXpathXPathFactory_DEFAULT_PROPERTY_NAME_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlXpathXPathFactory, DEFAULT_PROPERTY_NAME_, NSString *)

FOUNDATION_EXPORT NSString *JavaxXmlXpathXPathFactory_DEFAULT_OBJECT_MODEL_URI_;
J2OBJC_STATIC_FIELD_GETTER(JavaxXmlXpathXPathFactory, DEFAULT_OBJECT_MODEL_URI_, NSString *)

FOUNDATION_EXPORT void JavaxXmlXpathXPathFactory_init(JavaxXmlXpathXPathFactory *self);

FOUNDATION_EXPORT JavaxXmlXpathXPathFactory *JavaxXmlXpathXPathFactory_newInstance();

FOUNDATION_EXPORT JavaxXmlXpathXPathFactory *JavaxXmlXpathXPathFactory_newInstanceWithNSString_(NSString *uri);

FOUNDATION_EXPORT JavaxXmlXpathXPathFactory *JavaxXmlXpathXPathFactory_newInstanceWithNSString_withNSString_withJavaLangClassLoader_(NSString *uri, NSString *factoryClassName, JavaLangClassLoader *classLoader);

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlXpathXPathFactory)

#endif // _JavaxXmlXpathXPathFactory_H_
