//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/xpath/XPathException.java
//

#ifndef _JavaxXmlXpathXPathException_H_
#define _JavaxXmlXpathXPathException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

@class JavaIoPrintStream;
@class JavaIoPrintWriter;
@class JavaLangThrowable;

@interface JavaxXmlXpathXPathException : JavaLangException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

- (JavaLangThrowable *)getCause;

- (void)printStackTrace;

- (void)printStackTraceWithJavaIoPrintStream:(JavaIoPrintStream *)s;

- (void)printStackTraceWithJavaIoPrintWriter:(JavaIoPrintWriter *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlXpathXPathException)

FOUNDATION_EXPORT void JavaxXmlXpathXPathException_initWithNSString_(JavaxXmlXpathXPathException *self, NSString *message);

FOUNDATION_EXPORT JavaxXmlXpathXPathException *new_JavaxXmlXpathXPathException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxXmlXpathXPathException_initWithJavaLangThrowable_(JavaxXmlXpathXPathException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT JavaxXmlXpathXPathException *new_JavaxXmlXpathXPathException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlXpathXPathException)

#endif // _JavaxXmlXpathXPathException_H_
