//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/eventbus/EventBus.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonEventbusEventBus_INCLUDE_ALL")
#if ComGoogleCommonEventbusEventBus_RESTRICT
#define ComGoogleCommonEventbusEventBus_INCLUDE_ALL 0
#else
#define ComGoogleCommonEventbusEventBus_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonEventbusEventBus_RESTRICT

#if !defined (_ComGoogleCommonEventbusEventBus_) && (ComGoogleCommonEventbusEventBus_INCLUDE_ALL || ComGoogleCommonEventbusEventBus_INCLUDE)
#define _ComGoogleCommonEventbusEventBus_

@class ComGoogleCommonEventbusEventHandler;
@class IOSClass;
@protocol JavaUtilSet;

@interface ComGoogleCommonEventbusEventBus : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)identifier;

- (void)postWithId:(id)event;

- (void)register__WithId:(id)object;

- (void)unregisterWithId:(id)object;

#pragma mark Package-Private

- (void)dispatchWithId:(id)event
withComGoogleCommonEventbusEventHandler:(ComGoogleCommonEventbusEventHandler *)wrapper;

- (void)dispatchQueuedEvents;

- (void)enqueueEventWithId:(id)event
withComGoogleCommonEventbusEventHandler:(ComGoogleCommonEventbusEventHandler *)handler;

- (id<JavaUtilSet>)flattenHierarchyWithIOSClass:(IOSClass *)concreteClass;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonEventbusEventBus)

FOUNDATION_EXPORT void ComGoogleCommonEventbusEventBus_init(ComGoogleCommonEventbusEventBus *self);

FOUNDATION_EXPORT ComGoogleCommonEventbusEventBus *new_ComGoogleCommonEventbusEventBus_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleCommonEventbusEventBus_initWithNSString_(ComGoogleCommonEventbusEventBus *self, NSString *identifier);

FOUNDATION_EXPORT ComGoogleCommonEventbusEventBus *new_ComGoogleCommonEventbusEventBus_initWithNSString_(NSString *identifier) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonEventbusEventBus)

#endif

#if !defined (_ComGoogleCommonEventbusEventBus_EventWithHandler_) && (ComGoogleCommonEventbusEventBus_INCLUDE_ALL || ComGoogleCommonEventbusEventBus_EventWithHandler_INCLUDE)
#define _ComGoogleCommonEventbusEventBus_EventWithHandler_

@class ComGoogleCommonEventbusEventHandler;

@interface ComGoogleCommonEventbusEventBus_EventWithHandler : NSObject {
 @public
  id event_;
  ComGoogleCommonEventbusEventHandler *handler_;
}

#pragma mark Public

- (instancetype)initWithId:(id)event
withComGoogleCommonEventbusEventHandler:(ComGoogleCommonEventbusEventHandler *)handler;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonEventbusEventBus_EventWithHandler)

J2OBJC_FIELD_SETTER(ComGoogleCommonEventbusEventBus_EventWithHandler, event_, id)
J2OBJC_FIELD_SETTER(ComGoogleCommonEventbusEventBus_EventWithHandler, handler_, ComGoogleCommonEventbusEventHandler *)

FOUNDATION_EXPORT void ComGoogleCommonEventbusEventBus_EventWithHandler_initWithId_withComGoogleCommonEventbusEventHandler_(ComGoogleCommonEventbusEventBus_EventWithHandler *self, id event, ComGoogleCommonEventbusEventHandler *handler);

FOUNDATION_EXPORT ComGoogleCommonEventbusEventBus_EventWithHandler *new_ComGoogleCommonEventbusEventBus_EventWithHandler_initWithId_withComGoogleCommonEventbusEventHandler_(id event, ComGoogleCommonEventbusEventHandler *handler) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonEventbusEventBus_EventWithHandler)

#endif

#if !defined (_ComGoogleCommonEventbusEventBus_$1_) && (ComGoogleCommonEventbusEventBus_INCLUDE_ALL || ComGoogleCommonEventbusEventBus_$1_INCLUDE)
#define _ComGoogleCommonEventbusEventBus_$1_

#endif

#if !defined (_ComGoogleCommonEventbusEventBus_$2_) && (ComGoogleCommonEventbusEventBus_INCLUDE_ALL || ComGoogleCommonEventbusEventBus_$2_INCLUDE)
#define _ComGoogleCommonEventbusEventBus_$2_

#endif

#if !defined (_ComGoogleCommonEventbusEventBus_$3_) && (ComGoogleCommonEventbusEventBus_INCLUDE_ALL || ComGoogleCommonEventbusEventBus_$3_INCLUDE)
#define _ComGoogleCommonEventbusEventBus_$3_

#endif
#pragma pop_macro("ComGoogleCommonEventbusEventBus_INCLUDE_ALL")
