//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/os/SystemClock.java
//

#ifndef _AndroidOsSystemClock_H_
#define _AndroidOsSystemClock_H_

#include "J2ObjC_header.h"

@interface AndroidOsSystemClock : NSObject

#pragma mark Public

+ (jlong)currentTimeMicro;

+ (jlong)elapsedRealtime;

+ (jlong)elapsedRealtimeNanos;

+ (jboolean)setCurrentTimeMillisWithLong:(jlong)millis;

+ (void)sleepWithLong:(jlong)ms;

+ (jlong)uptimeMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidOsSystemClock)

FOUNDATION_EXPORT void AndroidOsSystemClock_sleepWithLong_(jlong ms);

FOUNDATION_EXPORT jboolean AndroidOsSystemClock_setCurrentTimeMillisWithLong_(jlong millis);

FOUNDATION_EXPORT jlong AndroidOsSystemClock_uptimeMillis();

FOUNDATION_EXPORT jlong AndroidOsSystemClock_elapsedRealtime();

FOUNDATION_EXPORT jlong AndroidOsSystemClock_elapsedRealtimeNanos();

FOUNDATION_EXPORT jlong AndroidOsSystemClock_currentTimeMicro();

J2OBJC_TYPE_LITERAL_HEADER(AndroidOsSystemClock)

#endif // _AndroidOsSystemClock_H_
