//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/controller/MapViewController.java
//

#ifndef _OrgMapsforgeMapControllerMapViewController_H_
#define _OrgMapsforgeMapControllerMapViewController_H_

#include "J2ObjC_header.h"
#include "org/mapsforge/map/model/common/Observer.h"

@class OrgMapsforgeMapModelModel;
@protocol OrgMapsforgeMapViewMapView;

@interface OrgMapsforgeMapControllerMapViewController : NSObject < OrgMapsforgeMapModelCommonObserver >

#pragma mark Public

+ (OrgMapsforgeMapControllerMapViewController *)createWithOrgMapsforgeMapViewMapView:(id<OrgMapsforgeMapViewMapView>)mapView
                                                       withOrgMapsforgeMapModelModel:(OrgMapsforgeMapModelModel *)model;

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapControllerMapViewController)

FOUNDATION_EXPORT OrgMapsforgeMapControllerMapViewController *OrgMapsforgeMapControllerMapViewController_createWithOrgMapsforgeMapViewMapView_withOrgMapsforgeMapModelModel_(id<OrgMapsforgeMapViewMapView> mapView, OrgMapsforgeMapModelModel *model);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapControllerMapViewController)

#endif // _OrgMapsforgeMapControllerMapViewController_H_
