//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/NoConnectionPendingException.java
//

#ifndef _JavaNioChannelsNoConnectionPendingException_H_
#define _JavaNioChannelsNoConnectionPendingException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalStateException.h"

@interface JavaNioChannelsNoConnectionPendingException : JavaLangIllegalStateException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioChannelsNoConnectionPendingException)

FOUNDATION_EXPORT void JavaNioChannelsNoConnectionPendingException_init(JavaNioChannelsNoConnectionPendingException *self);

FOUNDATION_EXPORT JavaNioChannelsNoConnectionPendingException *new_JavaNioChannelsNoConnectionPendingException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioChannelsNoConnectionPendingException)

#endif // _JavaNioChannelsNoConnectionPendingException_H_
