//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/NonWritableChannelException.java
//

#ifndef _JavaNioChannelsNonWritableChannelException_H_
#define _JavaNioChannelsNonWritableChannelException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalStateException.h"

@interface JavaNioChannelsNonWritableChannelException : JavaLangIllegalStateException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioChannelsNonWritableChannelException)

FOUNDATION_EXPORT void JavaNioChannelsNonWritableChannelException_init(JavaNioChannelsNonWritableChannelException *self);

FOUNDATION_EXPORT JavaNioChannelsNonWritableChannelException *new_JavaNioChannelsNonWritableChannelException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioChannelsNonWritableChannelException)

#endif // _JavaNioChannelsNonWritableChannelException_H_
