//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/NotYetBoundException.java
//

#ifndef _JavaNioChannelsNotYetBoundException_H_
#define _JavaNioChannelsNotYetBoundException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalStateException.h"

@interface JavaNioChannelsNotYetBoundException : JavaLangIllegalStateException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioChannelsNotYetBoundException)

FOUNDATION_EXPORT void JavaNioChannelsNotYetBoundException_init(JavaNioChannelsNotYetBoundException *self);

FOUNDATION_EXPORT JavaNioChannelsNotYetBoundException *new_JavaNioChannelsNotYetBoundException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioChannelsNotYetBoundException)

#endif // _JavaNioChannelsNotYetBoundException_H_
