//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/LineSegment.java
//

#ifndef _OrgMapsforgeCoreModelLineSegment_H_
#define _OrgMapsforgeCoreModelLineSegment_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;

@interface OrgMapsforgeCoreModelLineSegment : NSObject {
 @public
  OrgMapsforgeCoreModelPoint *start_;
  OrgMapsforgeCoreModelPoint *end_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)start
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)end;

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)start
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)direction
                                        withDouble:(jdouble)distance;

- (OrgMapsforgeCoreModelLineSegment *)clipToRectangleWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (jboolean)intersectsRectangleWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r
                                                      withBoolean:(jboolean)bias;

- (jdouble)length;

- (OrgMapsforgeCoreModelPoint *)pointAlongLineSegmentWithDouble:(jdouble)distance;

- (OrgMapsforgeCoreModelLineSegment *)reverse;

- (OrgMapsforgeCoreModelLineSegment *)subSegmentWithDouble:(jdouble)offset
                                                withDouble:(jdouble)length;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelLineSegment)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelLineSegment, start_, OrgMapsforgeCoreModelPoint *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelLineSegment, end_, OrgMapsforgeCoreModelPoint *)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelLineSegment *self, OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *end);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *new_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *end) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withDouble_(OrgMapsforgeCoreModelLineSegment *self, OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *direction, jdouble distance);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *new_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withDouble_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *direction, jdouble distance) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelLineSegment)

#endif // _OrgMapsforgeCoreModelLineSegment_H_
