//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Tag.java
//

#ifndef _OrgMapsforgeCoreModelTag_H_
#define _OrgMapsforgeCoreModelTag_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface OrgMapsforgeCoreModelTag : NSObject < JavaIoSerializable > {
 @public
  NSString *key_;
  NSString *value_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)tag;

- (instancetype)initWithNSString:(NSString *)key
                    withNSString:(NSString *)value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelTag)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelTag, key_, NSString *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelTag, value_, NSString *)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelTag_initWithNSString_(OrgMapsforgeCoreModelTag *self, NSString *tag);

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *new_OrgMapsforgeCoreModelTag_initWithNSString_(NSString *tag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgMapsforgeCoreModelTag_initWithNSString_withNSString_(OrgMapsforgeCoreModelTag *self, NSString *key, NSString *value);

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *new_OrgMapsforgeCoreModelTag_initWithNSString_withNSString_(NSString *key, NSString *value) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelTag)

#endif // _OrgMapsforgeCoreModelTag_H_
