//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/util/SparseArray.java
//

#ifndef _AndroidUtilSparseArray_H_
#define _AndroidUtilSparseArray_H_

#include "J2ObjC_header.h"

@interface AndroidUtilSparseArray : NSObject < NSCopying >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)initialCapacity;

- (void)appendWithInt:(jint)key
               withId:(id)value;

- (void)clear;

- (AndroidUtilSparseArray *)clone;

- (void)delete__WithInt:(jint)key;

- (id)getWithInt:(jint)key;

- (id)getWithInt:(jint)key
          withId:(id)valueIfKeyNotFound;

- (jint)indexOfKeyWithInt:(jint)key;

- (jint)indexOfValueWithId:(id)value;

- (jint)keyAtWithInt:(jint)index;

- (void)putWithInt:(jint)key
            withId:(id)value;

- (void)removeWithInt:(jint)key;

- (void)removeAtWithInt:(jint)index;

- (void)removeAtRangeWithInt:(jint)index
                     withInt:(jint)size;

- (void)setValueAtWithInt:(jint)index
                   withId:(id)value;

- (jint)size;

- (NSString *)description;

- (id)valueAtWithInt:(jint)index;

@end

J2OBJC_STATIC_INIT(AndroidUtilSparseArray)

FOUNDATION_EXPORT void AndroidUtilSparseArray_init(AndroidUtilSparseArray *self);

FOUNDATION_EXPORT AndroidUtilSparseArray *new_AndroidUtilSparseArray_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void AndroidUtilSparseArray_initWithInt_(AndroidUtilSparseArray *self, jint initialCapacity);

FOUNDATION_EXPORT AndroidUtilSparseArray *new_AndroidUtilSparseArray_initWithInt_(jint initialCapacity) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilSparseArray)

#endif // _AndroidUtilSparseArray_H_
