//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/ASN1Integer.java
//

#ifndef _OrgApacheHarmonySecurityAsn1ASN1Integer_H_
#define _OrgApacheHarmonySecurityAsn1ASN1Integer_H_

#include "J2ObjC_header.h"
#include "org/apache/harmony/security/asn1/ASN1Primitive.h"

@class JavaMathBigInteger;
@class OrgApacheHarmonySecurityAsn1BerInputStream;
@class OrgApacheHarmonySecurityAsn1BerOutputStream;

@interface OrgApacheHarmonySecurityAsn1ASN1Integer : OrgApacheHarmonySecurityAsn1ASN1Primitive

#pragma mark Public

- (instancetype)init;

- (id)decodeWithOrgApacheHarmonySecurityAsn1BerInputStream:(OrgApacheHarmonySecurityAsn1BerInputStream *)inArg;

- (void)encodeContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

+ (id)fromIntValueWithInt:(jint)value;

- (id)getDecodedObjectWithOrgApacheHarmonySecurityAsn1BerInputStream:(OrgApacheHarmonySecurityAsn1BerInputStream *)inArg;

+ (OrgApacheHarmonySecurityAsn1ASN1Integer *)getInstance;

- (void)setEncodingContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

+ (JavaMathBigInteger *)toBigIntegerValueWithId:(id)decoded;

+ (jint)toIntValueWithId:(id)decoded;

@end

J2OBJC_STATIC_INIT(OrgApacheHarmonySecurityAsn1ASN1Integer)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1ASN1Integer_init(OrgApacheHarmonySecurityAsn1ASN1Integer *self);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Integer *new_OrgApacheHarmonySecurityAsn1ASN1Integer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Integer *OrgApacheHarmonySecurityAsn1ASN1Integer_getInstance();

FOUNDATION_EXPORT jint OrgApacheHarmonySecurityAsn1ASN1Integer_toIntValueWithId_(id decoded);

FOUNDATION_EXPORT JavaMathBigInteger *OrgApacheHarmonySecurityAsn1ASN1Integer_toBigIntegerValueWithId_(id decoded);

FOUNDATION_EXPORT id OrgApacheHarmonySecurityAsn1ASN1Integer_fromIntValueWithInt_(jint value);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityAsn1ASN1Integer)

#endif // _OrgApacheHarmonySecurityAsn1ASN1Integer_H_
