//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/ASN1Type.java
//

#ifndef _OrgApacheHarmonySecurityAsn1ASN1Type_H_
#define _OrgApacheHarmonySecurityAsn1ASN1Type_H_

#include "J2ObjC_header.h"
#include "org/apache/harmony/security/asn1/ASN1Constants.h"

@class IOSByteArray;
@class JavaIoInputStream;
@class OrgApacheHarmonySecurityAsn1BerInputStream;
@class OrgApacheHarmonySecurityAsn1BerOutputStream;

@interface OrgApacheHarmonySecurityAsn1ASN1Type : NSObject < OrgApacheHarmonySecurityAsn1ASN1Constants > {
 @public
  jint id__;
  jint constrId_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)tagNumber;

- (instancetype)initWithInt:(jint)tagClass
                    withInt:(jint)tagNumber;

- (jboolean)checkTagWithInt:(jint)identifier;

- (id)decodeWithOrgApacheHarmonySecurityAsn1BerInputStream:(OrgApacheHarmonySecurityAsn1BerInputStream *)inArg;

- (id)decodeWithByteArray:(IOSByteArray *)encoded;

- (id)decodeWithByteArray:(IOSByteArray *)encoded
                  withInt:(jint)offset
                  withInt:(jint)encodingLen;

- (id)decodeWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (IOSByteArray *)encodeWithId:(id)object;

- (void)encodeASNWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

- (void)encodeContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

- (jint)getEncodedLengthWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

- (void)setEncodingContentWithOrgApacheHarmonySecurityAsn1BerOutputStream:(OrgApacheHarmonySecurityAsn1BerOutputStream *)outArg;

- (NSString *)description;

- (void)verifyWithByteArray:(IOSByteArray *)encoded;

- (void)verifyWithJavaIoInputStream:(JavaIoInputStream *)inArg;

#pragma mark Protected

- (id)getDecodedObjectWithOrgApacheHarmonySecurityAsn1BerInputStream:(OrgApacheHarmonySecurityAsn1BerInputStream *)inArg;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonySecurityAsn1ASN1Type)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1ASN1Type_initWithInt_(OrgApacheHarmonySecurityAsn1ASN1Type *self, jint tagNumber);

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1ASN1Type_initWithInt_withInt_(OrgApacheHarmonySecurityAsn1ASN1Type *self, jint tagClass, jint tagNumber);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityAsn1ASN1Type)

#endif // _OrgApacheHarmonySecurityAsn1ASN1Type_H_
