//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/BerInputStream.java
//

#ifndef _OrgApacheHarmonySecurityAsn1BerInputStream_H_
#define _OrgApacheHarmonySecurityAsn1BerInputStream_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@class IOSIntArray;
@class JavaIoInputStream;
@class OrgApacheHarmonySecurityAsn1ASN1Sequence;
@class OrgApacheHarmonySecurityAsn1ASN1SequenceOf;
@class OrgApacheHarmonySecurityAsn1ASN1Set;
@class OrgApacheHarmonySecurityAsn1ASN1SetOf;
@class OrgApacheHarmonySecurityAsn1ASN1StringType;

#define OrgApacheHarmonySecurityAsn1BerInputStream_INDEFINIT_LENGTH -1

@interface OrgApacheHarmonySecurityAsn1BerInputStream : NSObject {
 @public
  IOSByteArray *buffer_;
  jint offset_;
  jint tag_;
  jint length_;
  id content_;
  jint tagOffset_;
  jint contentOffset_;
  jint choiceIndex_;
  IOSIntArray *times_;
  jint oidElement_;
  jboolean isVerify_;
  jboolean isIndefinedLength_;
}

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)encoded;

- (instancetype)initWithByteArray:(IOSByteArray *)encoded
                          withInt:(jint)offset
                          withInt:(jint)expectedLength;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                  withInt:(jint)initialSize;

- (void)compactBuffer;

- (id)getWithId:(id)key;

- (IOSByteArray *)getBuffer;

- (IOSByteArray *)getEncoded;

- (jint)getEndOffset;

- (jint)getLength;

+ (jint)getLengthWithByteArray:(IOSByteArray *)encoding;

- (jint)getOffset;

- (jint)getTagOffset;

- (jint)next;

- (void)putWithId:(id)key
           withId:(id)entry_;

- (void)readBitString;

- (void)readBoolean;

- (void)readContent;

- (void)readEnumerated;

- (void)readGeneralizedTime;

- (void)readInteger;

- (void)readOctetString;

- (void)readOID;

- (void)readSequenceWithOrgApacheHarmonySecurityAsn1ASN1Sequence:(OrgApacheHarmonySecurityAsn1ASN1Sequence *)sequence;

- (void)readSequenceOfWithOrgApacheHarmonySecurityAsn1ASN1SequenceOf:(OrgApacheHarmonySecurityAsn1ASN1SequenceOf *)sequenceOf;

- (void)readSetWithOrgApacheHarmonySecurityAsn1ASN1Set:(OrgApacheHarmonySecurityAsn1ASN1Set *)set;

- (void)readSetOfWithOrgApacheHarmonySecurityAsn1ASN1SetOf:(OrgApacheHarmonySecurityAsn1ASN1SetOf *)setOf;

- (void)readStringWithOrgApacheHarmonySecurityAsn1ASN1StringType:(OrgApacheHarmonySecurityAsn1ASN1StringType *)type;

- (void)readUTCTime;

- (void)resetWithByteArray:(IOSByteArray *)encoded;

- (void)setVerify;

#pragma mark Protected

- (jint)read;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonySecurityAsn1BerInputStream)

J2OBJC_FIELD_SETTER(OrgApacheHarmonySecurityAsn1BerInputStream, buffer_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonySecurityAsn1BerInputStream, content_, id)
J2OBJC_FIELD_SETTER(OrgApacheHarmonySecurityAsn1BerInputStream, times_, IOSIntArray *)

J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonySecurityAsn1BerInputStream, INDEFINIT_LENGTH, jint)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1BerInputStream_initWithByteArray_(OrgApacheHarmonySecurityAsn1BerInputStream *self, IOSByteArray *encoded);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1BerInputStream *new_OrgApacheHarmonySecurityAsn1BerInputStream_initWithByteArray_(IOSByteArray *encoded) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1BerInputStream_initWithByteArray_withInt_withInt_(OrgApacheHarmonySecurityAsn1BerInputStream *self, IOSByteArray *encoded, jint offset, jint expectedLength);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1BerInputStream *new_OrgApacheHarmonySecurityAsn1BerInputStream_initWithByteArray_withInt_withInt_(IOSByteArray *encoded, jint offset, jint expectedLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1BerInputStream_initWithJavaIoInputStream_(OrgApacheHarmonySecurityAsn1BerInputStream *self, JavaIoInputStream *inArg);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1BerInputStream *new_OrgApacheHarmonySecurityAsn1BerInputStream_initWithJavaIoInputStream_(JavaIoInputStream *inArg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1BerInputStream_initWithJavaIoInputStream_withInt_(OrgApacheHarmonySecurityAsn1BerInputStream *self, JavaIoInputStream *inArg, jint initialSize);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1BerInputStream *new_OrgApacheHarmonySecurityAsn1BerInputStream_initWithJavaIoInputStream_withInt_(JavaIoInputStream *inArg, jint initialSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT jint OrgApacheHarmonySecurityAsn1BerInputStream_getLengthWithByteArray_(IOSByteArray *encoding);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityAsn1BerInputStream)

#endif // _OrgApacheHarmonySecurityAsn1BerInputStream_H_
