//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/mapelements/MapElementContainer.java
//

#ifndef _OrgMapsforgeCoreMapelementsMapElementContainer_H_
#define _OrgMapsforgeCoreMapelementsMapElementContainer_H_

#include "J2ObjC_header.h"
#include "java/lang/Comparable.h"

@class OrgMapsforgeCoreGraphicsDisplayEnum;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsMatrix;

@interface OrgMapsforgeCoreMapelementsMapElementContainer : NSObject < JavaLangComparable > {
 @public
  OrgMapsforgeCoreModelRectangle *boundary_;
  OrgMapsforgeCoreModelRectangle *boundaryAbsolute_;
  OrgMapsforgeCoreGraphicsDisplayEnum *display_;
  jint priority_;
  OrgMapsforgeCoreModelPoint *xy_;
}

#pragma mark Public

- (jboolean)clashesWithWithOrgMapsforgeCoreMapelementsMapElementContainer:(OrgMapsforgeCoreMapelementsMapElementContainer *)other;

- (jint)compareToWithId:(OrgMapsforgeCoreMapelementsMapElementContainer *)other;

- (void)drawWithOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas
                withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin
            withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix;

- (jboolean)isEqual:(id)obj;

- (OrgMapsforgeCoreModelPoint *)getPoint;

- (jint)getPriority;

- (NSUInteger)hash;

- (jboolean)intersectsWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)rectangle;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)xy
           withOrgMapsforgeCoreGraphicsDisplayEnum:(OrgMapsforgeCoreGraphicsDisplayEnum *)display
                                           withInt:(jint)priority;

- (OrgMapsforgeCoreModelRectangle *)getBoundaryAbsolute;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreMapelementsMapElementContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, boundary_, OrgMapsforgeCoreModelRectangle *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, boundaryAbsolute_, OrgMapsforgeCoreModelRectangle *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, display_, OrgMapsforgeCoreGraphicsDisplayEnum *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, xy_, OrgMapsforgeCoreModelPoint *)

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsMapElementContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplayEnum_withInt_(OrgMapsforgeCoreMapelementsMapElementContainer *self, OrgMapsforgeCoreModelPoint *xy, OrgMapsforgeCoreGraphicsDisplayEnum *display, jint priority);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreMapelementsMapElementContainer)

#endif // _OrgMapsforgeCoreMapelementsMapElementContainer_H_
