//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/helpers/AttributesImpl.java
//

#ifndef _OrgXmlSaxHelpersAttributesImpl_H_
#define _OrgXmlSaxHelpersAttributesImpl_H_

#include "J2ObjC_header.h"
#include "org/xml/sax/Attributes.h"

@class IOSObjectArray;

@interface OrgXmlSaxHelpersAttributesImpl : NSObject < OrgXmlSaxAttributes > {
 @public
  jint length_;
  IOSObjectArray *data_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)atts;

- (void)addAttributeWithNSString:(NSString *)uri
                    withNSString:(NSString *)localName
                    withNSString:(NSString *)qName
                    withNSString:(NSString *)type
                    withNSString:(NSString *)value;

- (void)clear;

- (jint)getIndexWithNSString:(NSString *)qName;

- (jint)getIndexWithNSString:(NSString *)uri
                withNSString:(NSString *)localName;

- (jint)getLength;

- (NSString *)getLocalNameWithInt:(jint)index;

- (NSString *)getQNameWithInt:(jint)index;

- (NSString *)getTypeWithInt:(jint)index;

- (NSString *)getTypeWithNSString:(NSString *)qName;

- (NSString *)getTypeWithNSString:(NSString *)uri
                     withNSString:(NSString *)localName;

- (NSString *)getURIWithInt:(jint)index;

- (NSString *)getValueWithInt:(jint)index;

- (NSString *)getValueWithNSString:(NSString *)qName;

- (NSString *)getValueWithNSString:(NSString *)uri
                      withNSString:(NSString *)localName;

- (void)removeAttributeWithInt:(jint)index;

- (void)setAttributeWithInt:(jint)index
               withNSString:(NSString *)uri
               withNSString:(NSString *)localName
               withNSString:(NSString *)qName
               withNSString:(NSString *)type
               withNSString:(NSString *)value;

- (void)setAttributesWithOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)atts;

- (void)setLocalNameWithInt:(jint)index
               withNSString:(NSString *)localName;

- (void)setQNameWithInt:(jint)index
           withNSString:(NSString *)qName;

- (void)setTypeWithInt:(jint)index
          withNSString:(NSString *)type;

- (void)setURIWithInt:(jint)index
         withNSString:(NSString *)uri;

- (void)setValueWithInt:(jint)index
           withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgXmlSaxHelpersAttributesImpl)

J2OBJC_FIELD_SETTER(OrgXmlSaxHelpersAttributesImpl, data_, IOSObjectArray *)

FOUNDATION_EXPORT void OrgXmlSaxHelpersAttributesImpl_init(OrgXmlSaxHelpersAttributesImpl *self);

FOUNDATION_EXPORT OrgXmlSaxHelpersAttributesImpl *new_OrgXmlSaxHelpersAttributesImpl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgXmlSaxHelpersAttributesImpl_initWithOrgXmlSaxAttributes_(OrgXmlSaxHelpersAttributesImpl *self, id<OrgXmlSaxAttributes> atts);

FOUNDATION_EXPORT OrgXmlSaxHelpersAttributesImpl *new_OrgXmlSaxHelpersAttributesImpl_initWithOrgXmlSaxAttributes_(id<OrgXmlSaxAttributes> atts) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgXmlSaxHelpersAttributesImpl)

#endif // _OrgXmlSaxHelpersAttributesImpl_H_
