//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/helpers/ParserFactory.java
//

#ifndef _OrgXmlSaxHelpersParserFactory_H_
#define _OrgXmlSaxHelpersParserFactory_H_

#include "J2ObjC_header.h"

@protocol OrgXmlSaxParser;

@interface OrgXmlSaxHelpersParserFactory : NSObject

#pragma mark Public

+ (id<OrgXmlSaxParser>)makeParser;

+ (id<OrgXmlSaxParser>)makeParserWithNSString:(NSString *)className_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgXmlSaxHelpersParserFactory)

FOUNDATION_EXPORT id<OrgXmlSaxParser> OrgXmlSaxHelpersParserFactory_makeParser();

FOUNDATION_EXPORT id<OrgXmlSaxParser> OrgXmlSaxHelpersParserFactory_makeParserWithNSString_(NSString *className_);

J2OBJC_TYPE_LITERAL_HEADER(OrgXmlSaxHelpersParserFactory)

#endif // _OrgXmlSaxHelpersParserFactory_H_
