//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/util/concurrent/ServiceManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL")
#if ComGoogleCommonUtilConcurrentServiceManager_RESTRICT
#define ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL 0
#else
#define ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentServiceManager_RESTRICT

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_

@class ComGoogleCommonCollectImmutableMap;
@class ComGoogleCommonCollectImmutableMultimap;
@class JavaUtilConcurrentTimeUnitEnum;
@protocol ComGoogleCommonUtilConcurrentServiceManager_Listener;
@protocol JavaLangIterable;
@protocol JavaUtilConcurrentExecutor;
@protocol JavaUtilSet;

@interface ComGoogleCommonUtilConcurrentServiceManager : NSObject

#pragma mark Public

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)services;

- (void)addListenerWithComGoogleCommonUtilConcurrentServiceManager_Listener:(id<ComGoogleCommonUtilConcurrentServiceManager_Listener>)listener
                                             withJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (void)awaitHealthy;

- (void)awaitHealthyWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

- (void)awaitStopped;

- (void)awaitStoppedWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

- (jboolean)isHealthy;

- (ComGoogleCommonCollectImmutableMultimap *)servicesByState;

- (ComGoogleCommonUtilConcurrentServiceManager *)startAsync;

- (ComGoogleCommonCollectImmutableMap *)startupTimes;

- (ComGoogleCommonUtilConcurrentServiceManager *)stopAsync;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSet:(id<JavaUtilSet>)services;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonUtilConcurrentServiceManager)

FOUNDATION_EXPORT void ComGoogleCommonUtilConcurrentServiceManager_initWithJavaLangIterable_(ComGoogleCommonUtilConcurrentServiceManager *self, id<JavaLangIterable> services);

FOUNDATION_EXPORT ComGoogleCommonUtilConcurrentServiceManager *new_ComGoogleCommonUtilConcurrentServiceManager_initWithJavaLangIterable_(id<JavaLangIterable> services) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleCommonUtilConcurrentServiceManager_initWithJavaUtilSet_(ComGoogleCommonUtilConcurrentServiceManager *self, id<JavaUtilSet> services);

FOUNDATION_EXPORT ComGoogleCommonUtilConcurrentServiceManager *new_ComGoogleCommonUtilConcurrentServiceManager_initWithJavaUtilSet_(id<JavaUtilSet> services) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentServiceManager)

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_Listener_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_Listener_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_Listener_

@protocol ComGoogleCommonUtilConcurrentService;

@protocol ComGoogleCommonUtilConcurrentServiceManager_Listener < NSObject, JavaObject >

- (void)healthy;

- (void)stopped;

- (void)failureWithComGoogleCommonUtilConcurrentService:(id<ComGoogleCommonUtilConcurrentService>)service;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonUtilConcurrentServiceManager_Listener)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentServiceManager_Listener)

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_AwaitHealthGuard_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_AwaitHealthGuard_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_AwaitHealthGuard_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_StoppedGuard_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_StoppedGuard_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_StoppedGuard_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_$1_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$1_$1_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_$1_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$2_$1_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_$1_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceManagerState_$3_$1_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ServiceListener_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ServiceListener_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ServiceListener_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_ListenerExecutorPair_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_ListenerExecutorPair_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_ListenerExecutorPair_

#endif

#if !defined (_ComGoogleCommonUtilConcurrentServiceManager_$1_) && (ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL || ComGoogleCommonUtilConcurrentServiceManager_$1_INCLUDE)
#define _ComGoogleCommonUtilConcurrentServiceManager_$1_

#endif
#pragma pop_macro("ComGoogleCommonUtilConcurrentServiceManager_INCLUDE_ALL")
