//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/junit/build_result/java/org/junit/rules/TestRule.java
//

#ifndef _OrgJunitRulesTestRule_H_
#define _OrgJunitRulesTestRule_H_

#include "J2ObjC_header.h"

@class OrgJunitRunnerDescription;
@class OrgJunitRunnersModelStatement;

@protocol OrgJunitRulesTestRule < NSObject, JavaObject >

- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                            withOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRulesTestRule)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRulesTestRule)

#endif // _OrgJunitRulesTestRule_H_
