//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/auth/callback/CallbackHandler.java
//

#ifndef _JavaxSecurityAuthCallbackCallbackHandler_H_
#define _JavaxSecurityAuthCallbackCallbackHandler_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;

@protocol JavaxSecurityAuthCallbackCallbackHandler < NSObject, JavaObject >

- (void)handleWithJavaxSecurityAuthCallbackCallbackArray:(IOSObjectArray *)callbacks;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityAuthCallbackCallbackHandler)

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityAuthCallbackCallbackHandler)

#endif // _JavaxSecurityAuthCallbackCallbackHandler_H_
