//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/auth/callback/PasswordCallback.java
//

#ifndef _JavaxSecurityAuthCallbackPasswordCallback_H_
#define _JavaxSecurityAuthCallbackPasswordCallback_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "javax/security/auth/callback/Callback.h"

@class IOSCharArray;

@interface JavaxSecurityAuthCallbackPasswordCallback : NSObject < JavaxSecurityAuthCallbackCallback, JavaIoSerializable > {
 @public
  jboolean echoOn_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)prompt
                     withBoolean:(jboolean)echoOn;

- (void)clearPassword;

- (IOSCharArray *)getPassword;

- (NSString *)getPrompt;

- (jboolean)isEchoOn;

- (void)setPasswordWithCharArray:(IOSCharArray *)password;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityAuthCallbackPasswordCallback)

FOUNDATION_EXPORT void JavaxSecurityAuthCallbackPasswordCallback_initWithNSString_withBoolean_(JavaxSecurityAuthCallbackPasswordCallback *self, NSString *prompt, jboolean echoOn);

FOUNDATION_EXPORT JavaxSecurityAuthCallbackPasswordCallback *new_JavaxSecurityAuthCallbackPasswordCallback_initWithNSString_withBoolean_(NSString *prompt, jboolean echoOn) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityAuthCallbackPasswordCallback)

#endif // _JavaxSecurityAuthCallbackPasswordCallback_H_
