//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/logging/Level.java
//

#ifndef _JavaUtilLoggingLevel_H_
#define _JavaUtilLoggingLevel_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface JavaUtilLoggingLevel : NSObject < JavaIoSerializable >

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (NSString *)getLocalizedName;

- (NSString *)getName;

- (NSString *)getResourceBundleName;

- (NSUInteger)hash;

- (jint)intValue;

+ (JavaUtilLoggingLevel *)parseWithNSString:(NSString *)name;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithNSString:(NSString *)name
                         withInt:(jint)level;

- (instancetype)initWithNSString:(NSString *)name
                         withInt:(jint)level
                    withNSString:(NSString *)resourceBundleName;

@end

J2OBJC_STATIC_INIT(JavaUtilLoggingLevel)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_OFF_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, OFF_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_SEVERE_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, SEVERE_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_WARNING_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, WARNING_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_INFO_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, INFO_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_CONFIG_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, CONFIG_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_FINE_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, FINE_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_FINER_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, FINER_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_FINEST_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, FINEST_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_ALL_;
J2OBJC_STATIC_FIELD_GETTER(JavaUtilLoggingLevel, ALL_, JavaUtilLoggingLevel *)

FOUNDATION_EXPORT JavaUtilLoggingLevel *JavaUtilLoggingLevel_parseWithNSString_(NSString *name);

FOUNDATION_EXPORT void JavaUtilLoggingLevel_initWithNSString_withInt_(JavaUtilLoggingLevel *self, NSString *name, jint level);

FOUNDATION_EXPORT JavaUtilLoggingLevel *new_JavaUtilLoggingLevel_initWithNSString_withInt_(NSString *name, jint level) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilLoggingLevel_initWithNSString_withInt_withNSString_(JavaUtilLoggingLevel *self, NSString *name, jint level, NSString *resourceBundleName);

FOUNDATION_EXPORT JavaUtilLoggingLevel *new_JavaUtilLoggingLevel_initWithNSString_withInt_withNSString_(NSString *name, jint level, NSString *resourceBundleName) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilLoggingLevel)

#endif // _JavaUtilLoggingLevel_H_
