//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/dalvik/src/main/java/dalvik/system/CloseGuard.java
//

#ifndef _DalvikSystemCloseGuard_H_
#define _DalvikSystemCloseGuard_H_

#include "J2ObjC_header.h"

@class JavaLangThrowable;
@protocol DalvikSystemCloseGuard_Reporter;

@interface DalvikSystemCloseGuard : NSObject

#pragma mark Public

- (void)close;

+ (DalvikSystemCloseGuard *)get;

+ (id<DalvikSystemCloseGuard_Reporter>)getReporter;

- (void)openWithNSString:(NSString *)closer;

+ (void)setEnabledWithBoolean:(jboolean)enabled;

+ (void)setReporterWithDalvikSystemCloseGuard_Reporter:(id<DalvikSystemCloseGuard_Reporter>)reporter;

- (void)warnIfOpen;

@end

J2OBJC_STATIC_INIT(DalvikSystemCloseGuard)

FOUNDATION_EXPORT DalvikSystemCloseGuard *DalvikSystemCloseGuard_get();

FOUNDATION_EXPORT void DalvikSystemCloseGuard_setEnabledWithBoolean_(jboolean enabled);

FOUNDATION_EXPORT void DalvikSystemCloseGuard_setReporterWithDalvikSystemCloseGuard_Reporter_(id<DalvikSystemCloseGuard_Reporter> reporter);

FOUNDATION_EXPORT id<DalvikSystemCloseGuard_Reporter> DalvikSystemCloseGuard_getReporter();

J2OBJC_TYPE_LITERAL_HEADER(DalvikSystemCloseGuard)

@protocol DalvikSystemCloseGuard_Reporter < NSObject, JavaObject >

- (void)reportWithNSString:(NSString *)message
     withJavaLangThrowable:(JavaLangThrowable *)allocationSite;

@end

J2OBJC_EMPTY_STATIC_INIT(DalvikSystemCloseGuard_Reporter)

J2OBJC_TYPE_LITERAL_HEADER(DalvikSystemCloseGuard_Reporter)

#endif // _DalvikSystemCloseGuard_H_
