//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/Deserializer.java
//

#ifndef _OrgMapsforgeMapReaderDeserializer_H_
#define _OrgMapsforgeMapReaderDeserializer_H_

#include "J2ObjC_header.h"

@class IOSByteArray;

@interface OrgMapsforgeMapReaderDeserializer : NSObject

#pragma mark Package-Private

+ (jlong)getFiveBytesLongWithByteArray:(IOSByteArray *)buffer
                               withInt:(jint)offset;

+ (jint)getIntWithByteArray:(IOSByteArray *)buffer
                    withInt:(jint)offset;

+ (jlong)getLongWithByteArray:(IOSByteArray *)buffer
                      withInt:(jint)offset;

+ (jint)getShortWithByteArray:(IOSByteArray *)buffer
                      withInt:(jint)offset;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderDeserializer)

FOUNDATION_EXPORT jlong OrgMapsforgeMapReaderDeserializer_getFiveBytesLongWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jint OrgMapsforgeMapReaderDeserializer_getIntWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jlong OrgMapsforgeMapReaderDeserializer_getLongWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

FOUNDATION_EXPORT jint OrgMapsforgeMapReaderDeserializer_getShortWithByteArray_withInt_(IOSByteArray *buffer, jint offset);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderDeserializer)

#endif // _OrgMapsforgeMapReaderDeserializer_H_
