//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/IndexCacheEntryKey.java
//

#ifndef _OrgMapsforgeMapReaderIndexCacheEntryKey_H_
#define _OrgMapsforgeMapReaderIndexCacheEntryKey_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeMapReaderHeaderSubFileParameter;

@interface OrgMapsforgeMapReaderIndexCacheEntryKey : NSObject

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapReaderHeaderSubFileParameter:(OrgMapsforgeMapReaderHeaderSubFileParameter *)subFileParameter
                                                           withLong:(jlong)indexBlockNumber;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderIndexCacheEntryKey)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderIndexCacheEntryKey_initWithOrgMapsforgeMapReaderHeaderSubFileParameter_withLong_(OrgMapsforgeMapReaderIndexCacheEntryKey *self, OrgMapsforgeMapReaderHeaderSubFileParameter *subFileParameter, jlong indexBlockNumber);

FOUNDATION_EXPORT OrgMapsforgeMapReaderIndexCacheEntryKey *new_OrgMapsforgeMapReaderIndexCacheEntryKey_initWithOrgMapsforgeMapReaderHeaderSubFileParameter_withLong_(OrgMapsforgeMapReaderHeaderSubFileParameter *subFileParameter, jlong indexBlockNumber) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderIndexCacheEntryKey)

#endif // _OrgMapsforgeMapReaderIndexCacheEntryKey_H_
