//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/MapDataStore.java
//

#ifndef _OrgMapsforgeMapReaderMapDataStore_H_
#define _OrgMapsforgeMapReaderMapDataStore_H_

#include "J2ObjC_header.h"

@class JavaLangByte;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapReaderMapReadResult;

@protocol OrgMapsforgeMapReaderMapDataStore < NSObject, JavaObject >

- (OrgMapsforgeCoreModelBoundingBox *)boundingBox;

- (void)close;

- (jlong)getDataTimestampWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (OrgMapsforgeCoreModelLatLong *)startPosition;

- (JavaLangByte *)startZoomLevel;

- (OrgMapsforgeMapReaderMapReadResult *)readMapDataWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (jboolean)supportsTileWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderMapDataStore)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMapDataStore)

#endif // _OrgMapsforgeMapReaderMapDataStore_H_
