//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/MapReadResult.java
//

#ifndef _OrgMapsforgeMapReaderMapReadResult_H_
#define _OrgMapsforgeMapReaderMapReadResult_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeMapReaderMapReadResultBuilder;
@protocol JavaUtilList;

@interface OrgMapsforgeMapReaderMapReadResult : NSObject {
 @public
  jboolean isWater_;
  id<JavaUtilList> pointOfInterests_;
  id<JavaUtilList> ways_;
}

#pragma mark Package-Private

- (instancetype)initWithOrgMapsforgeMapReaderMapReadResultBuilder:(OrgMapsforgeMapReaderMapReadResultBuilder *)mapReadResultBuilder;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderMapReadResult)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderMapReadResult, pointOfInterests_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderMapReadResult, ways_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderMapReadResult_initWithOrgMapsforgeMapReaderMapReadResultBuilder_(OrgMapsforgeMapReaderMapReadResult *self, OrgMapsforgeMapReaderMapReadResultBuilder *mapReadResultBuilder);

FOUNDATION_EXPORT OrgMapsforgeMapReaderMapReadResult *new_OrgMapsforgeMapReaderMapReadResult_initWithOrgMapsforgeMapReaderMapReadResultBuilder_(OrgMapsforgeMapReaderMapReadResultBuilder *mapReadResultBuilder) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMapReadResult)

#endif // _OrgMapsforgeMapReaderMapReadResult_H_
