//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/MultiMapDataStore.java
//

#ifndef _OrgMapsforgeMapReaderMultiMapDataStore_H_
#define _OrgMapsforgeMapReaderMultiMapDataStore_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"
#include "org/mapsforge/map/reader/MapDataStore.h"

@class JavaLangByte;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelTile;
@class OrgMapsforgeMapReaderMapReadResult;
@class OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum;

@interface OrgMapsforgeMapReaderMultiMapDataStore : NSObject < OrgMapsforgeMapReaderMapDataStore >

#pragma mark Public

- (instancetype)initWithOrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum:(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *)dataPolicy;

- (void)addMapDataStoreWithOrgMapsforgeMapReaderMapDataStore:(id<OrgMapsforgeMapReaderMapDataStore>)mapDataStore
                                                 withBoolean:(jboolean)useStartZoomLevel
                                                 withBoolean:(jboolean)useStartPosition;

- (OrgMapsforgeCoreModelBoundingBox *)boundingBox;

- (void)close;

- (jlong)getDataTimestampWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (OrgMapsforgeMapReaderMapReadResult *)readMapDataWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

- (void)setStartPositionWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)startPosition;

- (void)setStartZoomLevelWithByte:(jbyte)startZoomLevel;

- (OrgMapsforgeCoreModelLatLong *)startPosition;

- (JavaLangByte *)startZoomLevel;

- (jboolean)supportsTileWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)tile;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderMultiMapDataStore)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderMultiMapDataStore_initWithOrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_(OrgMapsforgeMapReaderMultiMapDataStore *self, OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *dataPolicy);

FOUNDATION_EXPORT OrgMapsforgeMapReaderMultiMapDataStore *new_OrgMapsforgeMapReaderMultiMapDataStore_initWithOrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *dataPolicy) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMultiMapDataStore)

typedef NS_ENUM(NSUInteger, OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy) {
  OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_RETURN_FIRST = 0,
  OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_RETURN_ALL = 1,
  OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_DEDUPLICATE = 2,
};

@interface OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_values();

+ (OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum)

FOUNDATION_EXPORT OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum *OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_values_[];

#define OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_RETURN_FIRST OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_values_[OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_RETURN_FIRST]
J2OBJC_ENUM_CONSTANT_GETTER(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum, RETURN_FIRST)

#define OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_RETURN_ALL OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_values_[OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_RETURN_ALL]
J2OBJC_ENUM_CONSTANT_GETTER(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum, RETURN_ALL)

#define OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_DEDUPLICATE OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum_values_[OrgMapsforgeMapReaderMultiMapDataStore_DataPolicy_DEDUPLICATE]
J2OBJC_ENUM_CONSTANT_GETTER(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum, DEDUPLICATE)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderMultiMapDataStore_DataPolicyEnum)

#endif // _OrgMapsforgeMapReaderMultiMapDataStore_H_
