//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/PointOfInterest.java
//

#ifndef _OrgMapsforgeMapReaderPointOfInterest_H_
#define _OrgMapsforgeMapReaderPointOfInterest_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreModelLatLong;
@protocol JavaUtilList;

@interface OrgMapsforgeMapReaderPointOfInterest : NSObject {
 @public
  jbyte layer_;
  OrgMapsforgeCoreModelLatLong *position_;
  id<JavaUtilList> tags_;
}

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithByte:(jbyte)layer
            withJavaUtilList:(id<JavaUtilList>)tags
withOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)position;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapReaderPointOfInterest)

J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderPointOfInterest, position_, OrgMapsforgeCoreModelLatLong *)
J2OBJC_FIELD_SETTER(OrgMapsforgeMapReaderPointOfInterest, tags_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(OrgMapsforgeMapReaderPointOfInterest *self, jbyte layer, id<JavaUtilList> tags, OrgMapsforgeCoreModelLatLong *position);

FOUNDATION_EXPORT OrgMapsforgeMapReaderPointOfInterest *new_OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(jbyte layer, id<JavaUtilList> tags, OrgMapsforgeCoreModelLatLong *position) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderPointOfInterest)

#endif // _OrgMapsforgeMapReaderPointOfInterest_H_
