//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/ReadBuffer.java
//

#ifndef _OrgMapsforgeMapReaderReadBuffer_H_
#define _OrgMapsforgeMapReaderReadBuffer_H_

#include "J2ObjC_header.h"

@class JavaIoRandomAccessFile;

#define OrgMapsforgeMapReaderReadBuffer_MAXIMUM_BUFFER_SIZE 2500000

@interface OrgMapsforgeMapReaderReadBuffer : NSObject

#pragma mark Public

- (jbyte)readByte;

- (jboolean)readFromFileWithInt:(jint)length;

- (jint)readInt;

- (jlong)readLong;

- (jint)readShort;

- (jint)readSignedInt;

- (jint)readUnsignedInt;

- (NSString *)readUTF8EncodedString;

- (NSString *)readUTF8EncodedStringWithInt:(jint)stringLength;

#pragma mark Package-Private

- (instancetype)initWithJavaIoRandomAccessFile:(JavaIoRandomAccessFile *)inputFile;

- (jint)getBufferPosition;

- (jint)getBufferSize;

- (void)setBufferPositionWithInt:(jint)bufferPosition;

- (void)skipBytesWithInt:(jint)bytes;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeMapReaderReadBuffer)

J2OBJC_STATIC_FIELD_GETTER(OrgMapsforgeMapReaderReadBuffer, MAXIMUM_BUFFER_SIZE, jint)

FOUNDATION_EXPORT void OrgMapsforgeMapReaderReadBuffer_initWithJavaIoRandomAccessFile_(OrgMapsforgeMapReaderReadBuffer *self, JavaIoRandomAccessFile *inputFile);

FOUNDATION_EXPORT OrgMapsforgeMapReaderReadBuffer *new_OrgMapsforgeMapReaderReadBuffer_initWithJavaIoRandomAccessFile_(JavaIoRandomAccessFile *inputFile) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapReaderReadBuffer)

#endif // _OrgMapsforgeMapReaderReadBuffer_H_
