//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/net/http/HttpDate.java
//

#ifndef _LibcoreNetHttpHttpDate_H_
#define _LibcoreNetHttpHttpDate_H_

#include "J2ObjC_header.h"

@class JavaUtilDate;

@interface LibcoreNetHttpHttpDate : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)formatWithJavaUtilDate:(JavaUtilDate *)value;

+ (JavaUtilDate *)parseWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(LibcoreNetHttpHttpDate)

FOUNDATION_EXPORT JavaUtilDate *LibcoreNetHttpHttpDate_parseWithNSString_(NSString *value);

FOUNDATION_EXPORT NSString *LibcoreNetHttpHttpDate_formatWithJavaUtilDate_(JavaUtilDate *value);

FOUNDATION_EXPORT void LibcoreNetHttpHttpDate_init(LibcoreNetHttpHttpDate *self);

FOUNDATION_EXPORT LibcoreNetHttpHttpDate *new_LibcoreNetHttpHttpDate_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(LibcoreNetHttpHttpDate)

#endif // _LibcoreNetHttpHttpDate_H_
