//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/common/Observer.java
//

#ifndef _OrgMapsforgeMapModelCommonObserver_H_
#define _OrgMapsforgeMapModelCommonObserver_H_

#include "J2ObjC_header.h"

@protocol OrgMapsforgeMapModelCommonObserver < NSObject, JavaObject >

- (void)onChange;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelCommonObserver)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelCommonObserver)

#endif // _OrgMapsforgeMapModelCommonObserver_H_
