//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/model/FrameBufferModel.java
//

#ifndef _OrgMapsforgeMapModelFrameBufferModel_H_
#define _OrgMapsforgeMapModelFrameBufferModel_H_

#include "J2ObjC_header.h"
#include "org/mapsforge/map/model/common/Observable.h"

@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeCoreModelMapPosition;

@interface OrgMapsforgeMapModelFrameBufferModel : OrgMapsforgeMapModelCommonObservable

#pragma mark Public

- (instancetype)init;

- (OrgMapsforgeCoreModelDimension *)getDimension;

- (OrgMapsforgeCoreModelMapPosition *)getMapPosition;

- (jdouble)getOverdrawFactor;

- (void)setDimensionWithOrgMapsforgeCoreModelDimension:(OrgMapsforgeCoreModelDimension *)dimension;

- (void)setMapPositionWithOrgMapsforgeCoreModelMapPosition:(OrgMapsforgeCoreModelMapPosition *)mapPosition;

- (void)setOverdrawFactorWithDouble:(jdouble)overdrawFactor;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapModelFrameBufferModel)

FOUNDATION_EXPORT void OrgMapsforgeMapModelFrameBufferModel_init(OrgMapsforgeMapModelFrameBufferModel *self);

FOUNDATION_EXPORT OrgMapsforgeMapModelFrameBufferModel *new_OrgMapsforgeMapModelFrameBufferModel_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapModelFrameBufferModel)

#endif // _OrgMapsforgeMapModelFrameBufferModel_H_
