//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/collect/EmptyImmutableMultiset.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE_ALL")
#if ComGoogleCommonCollectEmptyImmutableMultiset_RESTRICT
#define ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE_ALL 0
#else
#define ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectEmptyImmutableMultiset_RESTRICT

#if !defined (_ComGoogleCommonCollectEmptyImmutableMultiset_) && (ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE_ALL || ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE)
#define _ComGoogleCommonCollectEmptyImmutableMultiset_

#define ComGoogleCommonCollectImmutableMultiset_RESTRICT 1
#define ComGoogleCommonCollectImmutableMultiset_INCLUDE 1
#include "com/google/common/collect/ImmutableMultiset.h"

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonCollectUnmodifiableIterator;
@class IOSObjectArray;
@protocol JavaUtilCollection;

@interface ComGoogleCommonCollectEmptyImmutableMultiset : ComGoogleCommonCollectImmutableMultiset

#pragma mark Public

- (ComGoogleCommonCollectImmutableList *)asList;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)targets;

- (jint)countWithId:(id)element;

- (ComGoogleCommonCollectImmutableSet *)elementSet;

- (ComGoogleCommonCollectImmutableSet *)entrySet;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)other;

#pragma mark Package-Private

- (instancetype)init;

- (ComGoogleCommonCollectImmutableSet *)createEntrySet;

- (jboolean)isPartialView;

- (id)readResolve;


@end

J2OBJC_STATIC_INIT(ComGoogleCommonCollectEmptyImmutableMultiset)

FOUNDATION_EXPORT ComGoogleCommonCollectEmptyImmutableMultiset *ComGoogleCommonCollectEmptyImmutableMultiset_INSTANCE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectEmptyImmutableMultiset, INSTANCE_, ComGoogleCommonCollectEmptyImmutableMultiset *)

FOUNDATION_EXPORT void ComGoogleCommonCollectEmptyImmutableMultiset_init(ComGoogleCommonCollectEmptyImmutableMultiset *self);

FOUNDATION_EXPORT ComGoogleCommonCollectEmptyImmutableMultiset *new_ComGoogleCommonCollectEmptyImmutableMultiset_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectEmptyImmutableMultiset)

#endif
#pragma pop_macro("ComGoogleCommonCollectEmptyImmutableMultiset_INCLUDE_ALL")
