//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/collect/ImmutableEnumSet.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL")
#if ComGoogleCommonCollectImmutableEnumSet_RESTRICT
#define ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL 0
#else
#define ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectImmutableEnumSet_RESTRICT

#if !defined (_ComGoogleCommonCollectImmutableEnumSet_) && (ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL || ComGoogleCommonCollectImmutableEnumSet_INCLUDE)
#define _ComGoogleCommonCollectImmutableEnumSet_

#define ComGoogleCommonCollectImmutableSet_RESTRICT 1
#define ComGoogleCommonCollectImmutableSet_INCLUDE 1
#include "com/google/common/collect/ImmutableSet.h"

@class ComGoogleCommonCollectUnmodifiableIterator;
@class IOSObjectArray;
@class JavaUtilEnumSet;
@protocol JavaUtilCollection;

@interface ComGoogleCommonCollectImmutableEnumSet : ComGoogleCommonCollectImmutableSet

#pragma mark Public

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jboolean)isEmpty;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

- (NSString *)description;

#pragma mark Package-Private

+ (ComGoogleCommonCollectImmutableSet *)asImmutableWithJavaUtilEnumSet:(JavaUtilEnumSet *)set;

- (jboolean)isPartialView;

- (id)writeReplace;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectImmutableEnumSet)

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSet *ComGoogleCommonCollectImmutableEnumSet_asImmutableWithJavaUtilEnumSet_(JavaUtilEnumSet *set);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectImmutableEnumSet)

#endif

#if !defined (_ComGoogleCommonCollectImmutableEnumSet_EnumSerializedForm_) && (ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL || ComGoogleCommonCollectImmutableEnumSet_EnumSerializedForm_INCLUDE)
#define _ComGoogleCommonCollectImmutableEnumSet_EnumSerializedForm_

#endif
#pragma pop_macro("ComGoogleCommonCollectImmutableEnumSet_INCLUDE_ALL")
