//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/CookieManager.java
//

#ifndef _JavaNetCookieManager_H_
#define _JavaNetCookieManager_H_

#include "J2ObjC_header.h"
#include "java/net/CookieHandler.h"

@class JavaNetURI;
@protocol JavaNetCookiePolicy;
@protocol JavaNetCookieStore;
@protocol JavaUtilMap;

@interface JavaNetCookieManager : JavaNetCookieHandler

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaNetCookieStore:(id<JavaNetCookieStore>)store
                   withJavaNetCookiePolicy:(id<JavaNetCookiePolicy>)cookiePolicy;

- (id<JavaUtilMap>)getWithJavaNetURI:(JavaNetURI *)uri
                     withJavaUtilMap:(id<JavaUtilMap>)requestHeaders;

- (id<JavaNetCookieStore>)getCookieStore;

- (void)putWithJavaNetURI:(JavaNetURI *)uri
          withJavaUtilMap:(id<JavaUtilMap>)responseHeaders;

- (void)setCookiePolicyWithJavaNetCookiePolicy:(id<JavaNetCookiePolicy>)cookiePolicy;

#pragma mark Package-Private

+ (NSString *)pathToCookiePathWithNSString:(NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNetCookieManager)

FOUNDATION_EXPORT void JavaNetCookieManager_init(JavaNetCookieManager *self);

FOUNDATION_EXPORT JavaNetCookieManager *new_JavaNetCookieManager_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaNetCookieManager_initWithJavaNetCookieStore_withJavaNetCookiePolicy_(JavaNetCookieManager *self, id<JavaNetCookieStore> store, id<JavaNetCookiePolicy> cookiePolicy);

FOUNDATION_EXPORT JavaNetCookieManager *new_JavaNetCookieManager_initWithJavaNetCookieStore_withJavaNetCookiePolicy_(id<JavaNetCookieStore> store, id<JavaNetCookiePolicy> cookiePolicy) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NSString *JavaNetCookieManager_pathToCookiePathWithNSString_(NSString *path);

J2OBJC_TYPE_LITERAL_HEADER(JavaNetCookieManager)

#endif // _JavaNetCookieManager_H_
