//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/DatagramSocketImpl.java
//

#ifndef _JavaNetDatagramSocketImpl_H_
#define _JavaNetDatagramSocketImpl_H_

#include "J2ObjC_header.h"
#include "java/net/SocketOptions.h"

@class JavaIoFileDescriptor;
@class JavaNetDatagramPacket;
@class JavaNetInetAddress;
@class JavaNetNetworkInterface;
@class JavaNetSocketAddress;

@interface JavaNetDatagramSocketImpl : NSObject < JavaNetSocketOptions > {
 @public
  JavaIoFileDescriptor *fd_;
  jint localPort_;
}

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (void)bindWithInt:(jint)port
withJavaNetInetAddress:(JavaNetInetAddress *)addr;

- (void)close;

- (void)connectWithJavaNetInetAddress:(JavaNetInetAddress *)inetAddr
                              withInt:(jint)port;

- (void)create;

- (void)disconnect;

- (JavaIoFileDescriptor *)getFileDescriptor;

- (jint)getLocalPort;

- (jint)getTimeToLive;

- (jbyte)getTTL;

- (void)joinWithJavaNetInetAddress:(JavaNetInetAddress *)addr;

- (void)joinGroupWithJavaNetSocketAddress:(JavaNetSocketAddress *)addr
              withJavaNetNetworkInterface:(JavaNetNetworkInterface *)netInterface;

- (void)leaveWithJavaNetInetAddress:(JavaNetInetAddress *)addr;

- (void)leaveGroupWithJavaNetSocketAddress:(JavaNetSocketAddress *)addr
               withJavaNetNetworkInterface:(JavaNetNetworkInterface *)netInterface;

- (void)onBindWithJavaNetInetAddress:(JavaNetInetAddress *)localAddress
                             withInt:(jint)localPort;

- (void)onClose;

- (void)onConnectWithJavaNetInetAddress:(JavaNetInetAddress *)remoteAddress
                                withInt:(jint)remotePort;

- (void)onDisconnect;

- (jint)peekWithJavaNetInetAddress:(JavaNetInetAddress *)sender;

- (jint)peekDataWithJavaNetDatagramPacket:(JavaNetDatagramPacket *)pack;

- (void)receiveWithJavaNetDatagramPacket:(JavaNetDatagramPacket *)pack;

- (void)sendWithJavaNetDatagramPacket:(JavaNetDatagramPacket *)pack;

- (void)setTimeToLiveWithInt:(jint)ttl;

- (void)setTTLWithByte:(jbyte)ttl;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNetDatagramSocketImpl)

J2OBJC_FIELD_SETTER(JavaNetDatagramSocketImpl, fd_, JavaIoFileDescriptor *)

FOUNDATION_EXPORT void JavaNetDatagramSocketImpl_init(JavaNetDatagramSocketImpl *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaNetDatagramSocketImpl)

#endif // _JavaNetDatagramSocketImpl_H_
