//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/PortUnreachableException.java
//

#ifndef _JavaNetPortUnreachableException_H_
#define _JavaNetPortUnreachableException_H_

#include "J2ObjC_header.h"
#include "java/net/SocketException.h"

@class JavaLangThrowable;

@interface JavaNetPortUnreachableException : JavaNetSocketException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

- (instancetype)initWithNSString:(NSString *)detailMessage
           withJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNetPortUnreachableException)

FOUNDATION_EXPORT void JavaNetPortUnreachableException_init(JavaNetPortUnreachableException *self);

FOUNDATION_EXPORT JavaNetPortUnreachableException *new_JavaNetPortUnreachableException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaNetPortUnreachableException_initWithNSString_(JavaNetPortUnreachableException *self, NSString *detailMessage);

FOUNDATION_EXPORT JavaNetPortUnreachableException *new_JavaNetPortUnreachableException_initWithNSString_(NSString *detailMessage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaNetPortUnreachableException_initWithNSString_withJavaLangThrowable_(JavaNetPortUnreachableException *self, NSString *detailMessage, JavaLangThrowable *cause);

FOUNDATION_EXPORT JavaNetPortUnreachableException *new_JavaNetPortUnreachableException_initWithNSString_withJavaLangThrowable_(NSString *detailMessage, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNetPortUnreachableException)

#endif // _JavaNetPortUnreachableException_H_
