//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/junit/build_result/java/org/junit/After.java
//

#ifndef _OrgJunitAfter_H_
#define _OrgJunitAfter_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitAfter < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitAfter : NSObject < OrgJunitAfter >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitAfter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitAfter)

#endif // _OrgJunitAfter_H_
