//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/primitives/UnsignedBytes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE_ALL")
#if ComGoogleCommonPrimitivesUnsignedBytes_RESTRICT
#define ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE_ALL 0
#else
#define ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonPrimitivesUnsignedBytes_RESTRICT

#if !defined (_ComGoogleCommonPrimitivesUnsignedBytes_) && (ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE_ALL || ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE)
#define _ComGoogleCommonPrimitivesUnsignedBytes_

@class IOSByteArray;

#define ComGoogleCommonPrimitivesUnsignedBytes_MAX_POWER_OF_TWO -128
#define ComGoogleCommonPrimitivesUnsignedBytes_MAX_VALUE -1

@interface ComGoogleCommonPrimitivesUnsignedBytes : NSObject

#pragma mark Public

+ (jbyte)checkedCastWithLong:(jlong)value;

+ (jint)compareWithByte:(jbyte)a
               withByte:(jbyte)b;

+ (NSString *)joinWithNSString:(NSString *)separator
                 withByteArray:(IOSByteArray *)array;

+ (jbyte)maxWithByteArray:(IOSByteArray *)array;

+ (jbyte)minWithByteArray:(IOSByteArray *)array;

+ (jbyte)parseUnsignedByteWithNSString:(NSString *)string;

+ (jbyte)parseUnsignedByteWithNSString:(NSString *)string
                               withInt:(jint)radix;

+ (jbyte)saturatedCastWithLong:(jlong)value;

+ (jint)toIntWithByte:(jbyte)value;

+ (NSString *)toStringWithByte:(jbyte)x;

+ (NSString *)toStringWithByte:(jbyte)x
                       withInt:(jint)radix;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonPrimitivesUnsignedBytes)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonPrimitivesUnsignedBytes, MAX_POWER_OF_TWO, jbyte)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonPrimitivesUnsignedBytes, MAX_VALUE, jbyte)

FOUNDATION_EXPORT jint ComGoogleCommonPrimitivesUnsignedBytes_toIntWithByte_(jbyte value);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_checkedCastWithLong_(jlong value);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_saturatedCastWithLong_(jlong value);

FOUNDATION_EXPORT jint ComGoogleCommonPrimitivesUnsignedBytes_compareWithByte_withByte_(jbyte a, jbyte b);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_minWithByteArray_(IOSByteArray *array);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_maxWithByteArray_(IOSByteArray *array);

FOUNDATION_EXPORT NSString *ComGoogleCommonPrimitivesUnsignedBytes_toStringWithByte_(jbyte x);

FOUNDATION_EXPORT NSString *ComGoogleCommonPrimitivesUnsignedBytes_toStringWithByte_withInt_(jbyte x, jint radix);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_parseUnsignedByteWithNSString_(NSString *string);

FOUNDATION_EXPORT jbyte ComGoogleCommonPrimitivesUnsignedBytes_parseUnsignedByteWithNSString_withInt_(NSString *string, jint radix);

FOUNDATION_EXPORT NSString *ComGoogleCommonPrimitivesUnsignedBytes_joinWithNSString_withByteArray_(NSString *separator, IOSByteArray *array);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonPrimitivesUnsignedBytes)

#endif
#pragma pop_macro("ComGoogleCommonPrimitivesUnsignedBytes_INCLUDE_ALL")
