//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/GraphicContext.java
//

#ifndef _OrgMapsforgeCoreGraphicsGraphicContext_H_
#define _OrgMapsforgeCoreGraphicsGraphicContext_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreGraphicsColorEnum;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsMatrix;
@protocol OrgMapsforgeCoreGraphicsPaint;
@protocol OrgMapsforgeCoreGraphicsPath;

@protocol OrgMapsforgeCoreGraphicsGraphicContext < NSObject, JavaObject >

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                                             withInt:(jint)left
                                             withInt:(jint)top;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                  withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix;

- (void)drawCircleWithInt:(jint)x
                  withInt:(jint)y
                  withInt:(jint)radius
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawLineWithInt:(jint)x1
                withInt:(jint)y1
                withInt:(jint)x2
                withInt:(jint)y2
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawPathWithOrgMapsforgeCoreGraphicsPath:(id<OrgMapsforgeCoreGraphicsPath>)path
               withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawTextWithNSString:(NSString *)text
                     withInt:(jint)x
                     withInt:(jint)y
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawTextRotatedWithNSString:(NSString *)text
                            withInt:(jint)x1
                            withInt:(jint)y1
                            withInt:(jint)x2
                            withInt:(jint)y2
  withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)fillColorWithOrgMapsforgeCoreGraphicsColorEnum:(OrgMapsforgeCoreGraphicsColorEnum *)color;

- (void)fillColorWithInt:(jint)color;

- (void)resetClip;

- (void)setClipWithInt:(jint)left
               withInt:(jint)top
               withInt:(jint)width
               withInt:(jint)height;

- (void)setClipDifferenceWithInt:(jint)left
                         withInt:(jint)top
                         withInt:(jint)width
                         withInt:(jint)height;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsGraphicContext)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsGraphicContext)

#endif // _OrgMapsforgeCoreGraphicsGraphicContext_H_
