//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/EmulatedFieldsForLoading.java
//

#ifndef _JavaIoEmulatedFieldsForLoading_H_
#define _JavaIoEmulatedFieldsForLoading_H_

#include "J2ObjC_header.h"
#include "java/io/ObjectInputStream.h"

@class JavaIoEmulatedFields;
@class JavaIoObjectStreamClass;

@interface JavaIoEmulatedFieldsForLoading : JavaIoObjectInputStream_GetField

#pragma mark Public

- (jboolean)defaultedWithNSString:(NSString *)name;

- (jboolean)getWithNSString:(NSString *)name
                withBoolean:(jboolean)defaultValue;

- (jbyte)getWithNSString:(NSString *)name
                withByte:(jbyte)defaultValue;

- (jchar)getWithNSString:(NSString *)name
                withChar:(jchar)defaultValue;

- (jdouble)getWithNSString:(NSString *)name
                withDouble:(jdouble)defaultValue;

- (jfloat)getWithNSString:(NSString *)name
                withFloat:(jfloat)defaultValue;

- (jint)getWithNSString:(NSString *)name
                withInt:(jint)defaultValue;

- (jlong)getWithNSString:(NSString *)name
                withLong:(jlong)defaultValue;

- (id)getWithNSString:(NSString *)name
               withId:(id)defaultValue;

- (jshort)getWithNSString:(NSString *)name
                withShort:(jshort)defaultValue;

- (JavaIoObjectStreamClass *)getObjectStreamClass;

#pragma mark Package-Private

- (instancetype)initWithJavaIoObjectStreamClass:(JavaIoObjectStreamClass *)streamClass;

- (JavaIoEmulatedFields *)emulatedFields;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoEmulatedFieldsForLoading)

FOUNDATION_EXPORT void JavaIoEmulatedFieldsForLoading_initWithJavaIoObjectStreamClass_(JavaIoEmulatedFieldsForLoading *self, JavaIoObjectStreamClass *streamClass);

FOUNDATION_EXPORT JavaIoEmulatedFieldsForLoading *new_JavaIoEmulatedFieldsForLoading_initWithJavaIoObjectStreamClass_(JavaIoObjectStreamClass *streamClass) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaIoEmulatedFieldsForLoading)

#endif // _JavaIoEmulatedFieldsForLoading_H_
