//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/NotActiveException.java
//

#ifndef _JavaIoNotActiveException_H_
#define _JavaIoNotActiveException_H_

#include "J2ObjC_header.h"
#include "java/io/ObjectStreamException.h"

@interface JavaIoNotActiveException : JavaIoObjectStreamException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoNotActiveException)

FOUNDATION_EXPORT void JavaIoNotActiveException_init(JavaIoNotActiveException *self);

FOUNDATION_EXPORT JavaIoNotActiveException *new_JavaIoNotActiveException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaIoNotActiveException_initWithNSString_(JavaIoNotActiveException *self, NSString *detailMessage);

FOUNDATION_EXPORT JavaIoNotActiveException *new_JavaIoNotActiveException_initWithNSString_(NSString *detailMessage) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaIoNotActiveException)

#endif // _JavaIoNotActiveException_H_
