//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/ObjectOutputStream.java
//

#ifndef _JavaIoObjectOutputStream_H_
#define _JavaIoObjectOutputStream_H_

#include "J2ObjC_header.h"
#include "java/io/ObjectOutput.h"
#include "java/io/ObjectStreamConstants.h"
#include "java/io/OutputStream.h"

@class IOSByteArray;
@class IOSClass;
@class JavaIoObjectOutputStream_PutField;
@class JavaIoObjectStreamClass;

@interface JavaIoObjectOutputStream : JavaIoOutputStream < JavaIoObjectOutput, JavaIoObjectStreamConstants >

#pragma mark Public

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)output;

- (void)close;

- (void)defaultWriteObject;

- (void)flush;

- (JavaIoObjectOutputStream_PutField *)putFields;

- (void)reset;

- (void)useProtocolVersionWithInt:(jint)version_;

- (void)writeWithByteArray:(IOSByteArray *)buffer
                   withInt:(jint)offset
                   withInt:(jint)length;

- (void)writeWithInt:(jint)value;

- (void)writeBooleanWithBoolean:(jboolean)value;

- (void)writeByteWithInt:(jint)value;

- (void)writeBytesWithNSString:(NSString *)value;

- (void)writeCharWithInt:(jint)value;

- (void)writeCharsWithNSString:(NSString *)value;

- (void)writeDoubleWithDouble:(jdouble)value;

- (void)writeFields;

- (void)writeFloatWithFloat:(jfloat)value;

- (void)writeIntWithInt:(jint)value;

- (void)writeLongWithLong:(jlong)value;

- (void)writeObjectWithId:(id)object;

- (void)writeShortWithInt:(jint)value;

- (void)writeUnsharedWithId:(id)object;

- (void)writeUTFWithNSString:(NSString *)value;

#pragma mark Protected

- (instancetype)init;

- (void)annotateClassWithIOSClass:(IOSClass *)aClass;

- (void)annotateProxyClassWithIOSClass:(IOSClass *)aClass;

- (void)drain;

- (jboolean)enableReplaceObjectWithBoolean:(jboolean)enable;

- (id)replaceObjectWithId:(id)object;

- (void)writeClassDescriptorWithJavaIoObjectStreamClass:(JavaIoObjectStreamClass *)classDesc;

- (void)writeObjectOverrideWithId:(id)object;

- (void)writeStreamHeader;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoObjectOutputStream)

FOUNDATION_EXPORT void JavaIoObjectOutputStream_init(JavaIoObjectOutputStream *self);

FOUNDATION_EXPORT JavaIoObjectOutputStream *new_JavaIoObjectOutputStream_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaIoObjectOutputStream_initWithJavaIoOutputStream_(JavaIoObjectOutputStream *self, JavaIoOutputStream *output);

FOUNDATION_EXPORT JavaIoObjectOutputStream *new_JavaIoObjectOutputStream_initWithJavaIoOutputStream_(JavaIoOutputStream *output) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaIoObjectOutputStream)

@interface JavaIoObjectOutputStream_PutField : NSObject

#pragma mark Public

- (instancetype)init;

- (void)putWithNSString:(NSString *)name
            withBoolean:(jboolean)value;

- (void)putWithNSString:(NSString *)name
               withByte:(jbyte)value;

- (void)putWithNSString:(NSString *)name
               withChar:(jchar)value;

- (void)putWithNSString:(NSString *)name
             withDouble:(jdouble)value;

- (void)putWithNSString:(NSString *)name
              withFloat:(jfloat)value;

- (void)putWithNSString:(NSString *)name
                withInt:(jint)value;

- (void)putWithNSString:(NSString *)name
               withLong:(jlong)value;

- (void)putWithNSString:(NSString *)name
                 withId:(id)value;

- (void)putWithNSString:(NSString *)name
              withShort:(jshort)value;

- (void)writeWithJavaIoObjectOutput:(id<JavaIoObjectOutput>)outArg;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoObjectOutputStream_PutField)

FOUNDATION_EXPORT void JavaIoObjectOutputStream_PutField_init(JavaIoObjectOutputStream_PutField *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaIoObjectOutputStream_PutField)

#endif // _JavaIoObjectOutputStream_H_
