//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/SSLEngine.java
//

#ifndef _JavaxNetSslSSLEngine_H_
#define _JavaxNetSslSSLEngine_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaNioByteBuffer;
@class JavaxNetSslSSLEngineResult;
@class JavaxNetSslSSLEngineResult_HandshakeStatusEnum;
@class JavaxNetSslSSLParameters;
@protocol JavaLangRunnable;
@protocol JavaxNetSslSSLSession;

@interface JavaxNetSslSSLEngine : NSObject

#pragma mark Public

- (void)beginHandshake;

- (void)closeInbound;

- (void)closeOutbound;

- (id<JavaLangRunnable>)getDelegatedTask;

- (IOSObjectArray *)getEnabledCipherSuites;

- (IOSObjectArray *)getEnabledProtocols;

- (jboolean)getEnableSessionCreation;

- (JavaxNetSslSSLEngineResult_HandshakeStatusEnum *)getHandshakeStatus;

- (jboolean)getNeedClientAuth;

- (NSString *)getPeerHost;

- (jint)getPeerPort;

- (id<JavaxNetSslSSLSession>)getSession;

- (JavaxNetSslSSLParameters *)getSSLParameters;

- (IOSObjectArray *)getSupportedCipherSuites;

- (IOSObjectArray *)getSupportedProtocols;

- (jboolean)getUseClientMode;

- (jboolean)getWantClientAuth;

- (jboolean)isInboundDone;

- (jboolean)isOutboundDone;

- (void)setEnabledCipherSuitesWithNSStringArray:(IOSObjectArray *)suites;

- (void)setEnabledProtocolsWithNSStringArray:(IOSObjectArray *)protocols;

- (void)setEnableSessionCreationWithBoolean:(jboolean)flag;

- (void)setNeedClientAuthWithBoolean:(jboolean)need;

- (void)setSSLParametersWithJavaxNetSslSSLParameters:(JavaxNetSslSSLParameters *)p;

- (void)setUseClientModeWithBoolean:(jboolean)mode;

- (void)setWantClientAuthWithBoolean:(jboolean)want;

- (JavaxNetSslSSLEngineResult *)unwrapWithJavaNioByteBuffer:(JavaNioByteBuffer *)src
                                      withJavaNioByteBuffer:(JavaNioByteBuffer *)dst;

- (JavaxNetSslSSLEngineResult *)unwrapWithJavaNioByteBuffer:(JavaNioByteBuffer *)src
                                 withJavaNioByteBufferArray:(IOSObjectArray *)dsts;

- (JavaxNetSslSSLEngineResult *)unwrapWithJavaNioByteBuffer:(JavaNioByteBuffer *)src
                                 withJavaNioByteBufferArray:(IOSObjectArray *)dsts
                                                    withInt:(jint)offset
                                                    withInt:(jint)length;

- (JavaxNetSslSSLEngineResult *)wrapWithJavaNioByteBuffer:(JavaNioByteBuffer *)src
                                    withJavaNioByteBuffer:(JavaNioByteBuffer *)dst;

- (JavaxNetSslSSLEngineResult *)wrapWithJavaNioByteBufferArray:(IOSObjectArray *)srcs
                                         withJavaNioByteBuffer:(JavaNioByteBuffer *)dst;

- (JavaxNetSslSSLEngineResult *)wrapWithJavaNioByteBufferArray:(IOSObjectArray *)srcs
                                                       withInt:(jint)offset
                                                       withInt:(jint)length
                                         withJavaNioByteBuffer:(JavaNioByteBuffer *)dst;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)host
                         withInt:(jint)port;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslSSLEngine)

FOUNDATION_EXPORT void JavaxNetSslSSLEngine_init(JavaxNetSslSSLEngine *self);

FOUNDATION_EXPORT void JavaxNetSslSSLEngine_initWithNSString_withInt_(JavaxNetSslSSLEngine *self, NSString *host, jint port);

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslSSLEngine)

#endif // _JavaxNetSslSSLEngine_H_
