//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/SSLParameters.java
//

#ifndef _JavaxNetSslSSLParameters_H_
#define _JavaxNetSslSSLParameters_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;

@interface JavaxNetSslSSLParameters : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)cipherSuites;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)cipherSuites
                    withNSStringArray:(IOSObjectArray *)protocols;

- (IOSObjectArray *)getCipherSuites;

- (jboolean)getNeedClientAuth;

- (IOSObjectArray *)getProtocols;

- (jboolean)getWantClientAuth;

- (void)setCipherSuitesWithNSStringArray:(IOSObjectArray *)cipherSuites;

- (void)setNeedClientAuthWithBoolean:(jboolean)needClientAuth;

- (void)setProtocolsWithNSStringArray:(IOSObjectArray *)protocols;

- (void)setWantClientAuthWithBoolean:(jboolean)wantClientAuth;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslSSLParameters)

FOUNDATION_EXPORT void JavaxNetSslSSLParameters_init(JavaxNetSslSSLParameters *self);

FOUNDATION_EXPORT JavaxNetSslSSLParameters *new_JavaxNetSslSSLParameters_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxNetSslSSLParameters_initWithNSStringArray_(JavaxNetSslSSLParameters *self, IOSObjectArray *cipherSuites);

FOUNDATION_EXPORT JavaxNetSslSSLParameters *new_JavaxNetSslSSLParameters_initWithNSStringArray_(IOSObjectArray *cipherSuites) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxNetSslSSLParameters_initWithNSStringArray_withNSStringArray_(JavaxNetSslSSLParameters *self, IOSObjectArray *cipherSuites, IOSObjectArray *protocols);

FOUNDATION_EXPORT JavaxNetSslSSLParameters *new_JavaxNetSslSSLParameters_initWithNSStringArray_withNSStringArray_(IOSObjectArray *cipherSuites, IOSObjectArray *protocols) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslSSLParameters)

#endif // _JavaxNetSslSSLParameters_H_
