//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/SSLProtocolException.java
//

#ifndef _JavaxNetSslSSLProtocolException_H_
#define _JavaxNetSslSSLProtocolException_H_

#include "J2ObjC_header.h"
#include "javax/net/ssl/SSLException.h"

@interface JavaxNetSslSSLProtocolException : JavaxNetSslSSLException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)reason;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslSSLProtocolException)

FOUNDATION_EXPORT void JavaxNetSslSSLProtocolException_initWithNSString_(JavaxNetSslSSLProtocolException *self, NSString *reason);

FOUNDATION_EXPORT JavaxNetSslSSLProtocolException *new_JavaxNetSslSSLProtocolException_initWithNSString_(NSString *reason) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslSSLProtocolException)

#endif // _JavaxNetSslSSLProtocolException_H_
