//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/TrustManager.java
//

#ifndef _JavaxNetSslTrustManager_H_
#define _JavaxNetSslTrustManager_H_

#include "J2ObjC_header.h"

@protocol JavaxNetSslTrustManager < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslTrustManager)

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslTrustManager)

#endif // _JavaxNetSslTrustManager_H_
