//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/cert/Certificate.java
//

#ifndef _JavaxSecurityCertCertificate_H_
#define _JavaxSecurityCertCertificate_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@protocol JavaSecurityPublicKey;

@interface JavaxSecurityCertCertificate : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)isEqual:(id)obj;

- (IOSByteArray *)getEncoded;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (NSUInteger)hash;

- (NSString *)description;

- (void)verifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key;

- (void)verifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key
                           withNSString:(NSString *)sigProvider;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityCertCertificate)

FOUNDATION_EXPORT void JavaxSecurityCertCertificate_init(JavaxSecurityCertCertificate *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityCertCertificate)

#endif // _JavaxSecurityCertCertificate_H_
