//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/locks/AbstractOwnableSynchronizer.java
//

#ifndef _JavaUtilConcurrentLocksAbstractOwnableSynchronizer_H_
#define _JavaUtilConcurrentLocksAbstractOwnableSynchronizer_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class JavaLangThread;

@interface JavaUtilConcurrentLocksAbstractOwnableSynchronizer : NSObject < JavaIoSerializable >

#pragma mark Protected

- (instancetype)init;

- (JavaLangThread *)getExclusiveOwnerThread;

- (void)setExclusiveOwnerThreadWithJavaLangThread:(JavaLangThread *)t;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilConcurrentLocksAbstractOwnableSynchronizer)

FOUNDATION_EXPORT void JavaUtilConcurrentLocksAbstractOwnableSynchronizer_init(JavaUtilConcurrentLocksAbstractOwnableSynchronizer *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilConcurrentLocksAbstractOwnableSynchronizer)

#endif // _JavaUtilConcurrentLocksAbstractOwnableSynchronizer_H_
