//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/io/ByteStreams.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonIoByteStreams_INCLUDE_ALL")
#if ComGoogleCommonIoByteStreams_RESTRICT
#define ComGoogleCommonIoByteStreams_INCLUDE_ALL 0
#else
#define ComGoogleCommonIoByteStreams_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoByteStreams_RESTRICT

#if !defined (_ComGoogleCommonIoByteStreams_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_INCLUDE)
#define _ComGoogleCommonIoByteStreams_

@class ComGoogleCommonHashHashCode;
@class ComGoogleCommonIoByteSink;
@class ComGoogleCommonIoByteSource;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol ComGoogleCommonHashHashFunction;
@protocol ComGoogleCommonIoByteArrayDataInput;
@protocol ComGoogleCommonIoByteArrayDataOutput;
@protocol ComGoogleCommonIoByteProcessor;
@protocol ComGoogleCommonIoInputSupplier;
@protocol ComGoogleCommonIoOutputSupplier;
@protocol JavaLangIterable;
@protocol JavaUtilZipChecksum;

@interface ComGoogleCommonIoByteStreams : NSObject

#pragma mark Public

+ (ComGoogleCommonIoByteSource *)asByteSourceWithByteArray:(IOSByteArray *)b;

+ (jlong)copy__WithJavaIoInputStream:(JavaIoInputStream *)from
              withJavaIoOutputStream:(JavaIoOutputStream *)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithJavaIoInputStream:(JavaIoInputStream *)from
 withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)from
                           withJavaIoOutputStream:(JavaIoOutputStream *)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)from
              withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to OBJC_METHOD_FAMILY_NONE;

+ (jboolean)equalWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier1
                 withComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier2;

+ (jlong)getChecksumWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                               withJavaUtilZipChecksum:(id<JavaUtilZipChecksum>)checksum;

+ (ComGoogleCommonHashHashCode *)hash__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                                      withComGoogleCommonHashHashFunction:(id<ComGoogleCommonHashHashFunction>)hashFunction;

+ (id<ComGoogleCommonIoInputSupplier>)joinWithComGoogleCommonIoInputSupplierArray:(IOSObjectArray *)suppliers;

+ (id<ComGoogleCommonIoInputSupplier>)joinWithJavaLangIterable:(id<JavaLangIterable>)suppliers;

+ (jlong)lengthWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (JavaIoInputStream *)limitWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                         withLong:(jlong)limit;

+ (id<ComGoogleCommonIoByteArrayDataInput>)newDataInputWithByteArray:(IOSByteArray *)bytes OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataInput>)newDataInputWithByteArray:(IOSByteArray *)bytes
                                                             withInt:(jint)start OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataOutput>)newDataOutput OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataOutput>)newDataOutputWithInt:(jint)size OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoInputSupplier>)newInputStreamSupplierWithByteArray:(IOSByteArray *)b OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoInputSupplier>)newInputStreamSupplierWithByteArray:(IOSByteArray *)b
                                                                  withInt:(jint)off
                                                                  withInt:(jint)len OBJC_METHOD_FAMILY_NONE;

+ (JavaIoOutputStream *)nullOutputStream;

+ (jint)readWithJavaIoInputStream:(JavaIoInputStream *)inArg
                    withByteArray:(IOSByteArray *)b
                          withInt:(jint)off
                          withInt:(jint)len;

+ (id)readBytesWithJavaIoInputStream:(JavaIoInputStream *)input
  withComGoogleCommonIoByteProcessor:(id<ComGoogleCommonIoByteProcessor>)processor;

+ (id)readBytesWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
               withComGoogleCommonIoByteProcessor:(id<ComGoogleCommonIoByteProcessor>)processor;

+ (void)readFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                         withByteArray:(IOSByteArray *)b;

+ (void)readFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                         withByteArray:(IOSByteArray *)b
                               withInt:(jint)off
                               withInt:(jint)len;

+ (void)skipFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                              withLong:(jlong)n;

+ (id<ComGoogleCommonIoInputSupplier>)sliceWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                                                                     withLong:(jlong)offset
                                                                     withLong:(jlong)length;

+ (IOSByteArray *)toByteArrayWithJavaIoInputStream:(JavaIoInputStream *)inArg;

+ (IOSByteArray *)toByteArrayWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (void)writeWithByteArray:(IOSByteArray *)from
withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to;

#pragma mark Package-Private

+ (ComGoogleCommonIoByteSink *)asByteSinkWithComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)supplier;

+ (ComGoogleCommonIoByteSource *)asByteSourceWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (id<ComGoogleCommonIoInputSupplier>)asInputSupplierWithComGoogleCommonIoByteSource:(ComGoogleCommonIoByteSource *)source;

+ (id<ComGoogleCommonIoOutputSupplier>)asOutputSupplierWithComGoogleCommonIoByteSink:(ComGoogleCommonIoByteSink *)sink;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonIoByteStreams)

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_newInputStreamSupplierWithByteArray_(IOSByteArray *b);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_newInputStreamSupplierWithByteArray_withInt_withInt_(IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT ComGoogleCommonIoByteSource *ComGoogleCommonIoByteStreams_asByteSourceWithByteArray_(IOSByteArray *b);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_writeWithByteArray_withComGoogleCommonIoOutputSupplier_(IOSByteArray *from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithComGoogleCommonIoInputSupplier_withComGoogleCommonIoOutputSupplier_(id<ComGoogleCommonIoInputSupplier> from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithComGoogleCommonIoInputSupplier_withJavaIoOutputStream_(id<ComGoogleCommonIoInputSupplier> from, JavaIoOutputStream *to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithJavaIoInputStream_withComGoogleCommonIoOutputSupplier_(JavaIoInputStream *from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithJavaIoInputStream_withJavaIoOutputStream_(JavaIoInputStream *from, JavaIoOutputStream *to);

FOUNDATION_EXPORT IOSByteArray *ComGoogleCommonIoByteStreams_toByteArrayWithJavaIoInputStream_(JavaIoInputStream *inArg);

FOUNDATION_EXPORT IOSByteArray *ComGoogleCommonIoByteStreams_toByteArrayWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataInput> ComGoogleCommonIoByteStreams_newDataInputWithByteArray_(IOSByteArray *bytes);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataInput> ComGoogleCommonIoByteStreams_newDataInputWithByteArray_withInt_(IOSByteArray *bytes, jint start);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataOutput> ComGoogleCommonIoByteStreams_newDataOutput();

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataOutput> ComGoogleCommonIoByteStreams_newDataOutputWithInt_(jint size);

FOUNDATION_EXPORT JavaIoOutputStream *ComGoogleCommonIoByteStreams_nullOutputStream();

FOUNDATION_EXPORT JavaIoInputStream *ComGoogleCommonIoByteStreams_limitWithJavaIoInputStream_withLong_(JavaIoInputStream *inArg, jlong limit);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_lengthWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT jboolean ComGoogleCommonIoByteStreams_equalWithComGoogleCommonIoInputSupplier_withComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier1, id<ComGoogleCommonIoInputSupplier> supplier2);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_readFullyWithJavaIoInputStream_withByteArray_(JavaIoInputStream *inArg, IOSByteArray *b);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_readFullyWithJavaIoInputStream_withByteArray_withInt_withInt_(JavaIoInputStream *inArg, IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_skipFullyWithJavaIoInputStream_withLong_(JavaIoInputStream *inArg, jlong n);

FOUNDATION_EXPORT id ComGoogleCommonIoByteStreams_readBytesWithComGoogleCommonIoInputSupplier_withComGoogleCommonIoByteProcessor_(id<ComGoogleCommonIoInputSupplier> supplier, id<ComGoogleCommonIoByteProcessor> processor);

FOUNDATION_EXPORT id ComGoogleCommonIoByteStreams_readBytesWithJavaIoInputStream_withComGoogleCommonIoByteProcessor_(JavaIoInputStream *input, id<ComGoogleCommonIoByteProcessor> processor);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_getChecksumWithComGoogleCommonIoInputSupplier_withJavaUtilZipChecksum_(id<ComGoogleCommonIoInputSupplier> supplier, id<JavaUtilZipChecksum> checksum);

FOUNDATION_EXPORT ComGoogleCommonHashHashCode *ComGoogleCommonIoByteStreams_hash__WithComGoogleCommonIoInputSupplier_withComGoogleCommonHashHashFunction_(id<ComGoogleCommonIoInputSupplier> supplier, id<ComGoogleCommonHashHashFunction> hashFunction);

FOUNDATION_EXPORT jint ComGoogleCommonIoByteStreams_readWithJavaIoInputStream_withByteArray_withInt_withInt_(JavaIoInputStream *inArg, IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_sliceWithComGoogleCommonIoInputSupplier_withLong_withLong_(id<ComGoogleCommonIoInputSupplier> supplier, jlong offset, jlong length);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_joinWithJavaLangIterable_(id<JavaLangIterable> suppliers);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_joinWithComGoogleCommonIoInputSupplierArray_(IOSObjectArray *suppliers);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_asInputSupplierWithComGoogleCommonIoByteSource_(ComGoogleCommonIoByteSource *source);

FOUNDATION_EXPORT id<ComGoogleCommonIoOutputSupplier> ComGoogleCommonIoByteStreams_asOutputSupplierWithComGoogleCommonIoByteSink_(ComGoogleCommonIoByteSink *sink);

FOUNDATION_EXPORT ComGoogleCommonIoByteSource *ComGoogleCommonIoByteStreams_asByteSourceWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT ComGoogleCommonIoByteSink *ComGoogleCommonIoByteStreams_asByteSinkWithComGoogleCommonIoOutputSupplier_(id<ComGoogleCommonIoOutputSupplier> supplier);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams)

#endif

#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayByteSource_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayByteSource_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayByteSource_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_LimitedInputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_LimitedInputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_LimitedInputStream_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$1_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$1_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$1_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$2_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$2_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$2_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$3_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$3_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$3_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$4_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$4_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$4_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$5_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$5_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$5_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$6_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$6_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$6_

#endif

#if !defined (_ComGoogleCommonIoByteStreams_$7_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$7_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$7_

#endif
#pragma pop_macro("ComGoogleCommonIoByteStreams_INCLUDE_ALL")
