//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cbrasseur/Documents/j2objc-0.9.7/guava/sources/com/google/common/io/LimitInputStream.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ComGoogleCommonIoLimitInputStream_INCLUDE_ALL")
#if ComGoogleCommonIoLimitInputStream_RESTRICT
#define ComGoogleCommonIoLimitInputStream_INCLUDE_ALL 0
#else
#define ComGoogleCommonIoLimitInputStream_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoLimitInputStream_RESTRICT

#if !defined (_ComGoogleCommonIoLimitInputStream_) && (ComGoogleCommonIoLimitInputStream_INCLUDE_ALL || ComGoogleCommonIoLimitInputStream_INCLUDE)
#define _ComGoogleCommonIoLimitInputStream_

#define JavaIoFilterInputStream_RESTRICT 1
#define JavaIoFilterInputStream_INCLUDE 1
#include "java/io/FilterInputStream.h"

@class IOSByteArray;
@class JavaIoInputStream;

@interface ComGoogleCommonIoLimitInputStream : JavaIoFilterInputStream

#pragma mark Public

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                 withLong:(jlong)limit;

- (jint)available;

- (void)markWithInt:(jint)readlimit;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)b
                  withInt:(jint)off
                  withInt:(jint)len;

- (void)reset;

- (jlong)skipWithLong:(jlong)n;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoLimitInputStream)

FOUNDATION_EXPORT void ComGoogleCommonIoLimitInputStream_initWithJavaIoInputStream_withLong_(ComGoogleCommonIoLimitInputStream *self, JavaIoInputStream *inArg, jlong limit);

FOUNDATION_EXPORT ComGoogleCommonIoLimitInputStream *new_ComGoogleCommonIoLimitInputStream_initWithJavaIoInputStream_withLong_(JavaIoInputStream *inArg, jlong limit) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoLimitInputStream)

#endif
#pragma pop_macro("ComGoogleCommonIoLimitInputStream_INCLUDE_ALL")
