//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/view/MapView.java
//

#ifndef _OrgMapsforgeMapViewMapView_H_
#define _OrgMapsforgeMapViewMapView_H_

#include "J2ObjC_header.h"

@class OrgMapsforgeCoreModelDimension;
@class OrgMapsforgeMapLayerLayerManager;
@class OrgMapsforgeMapModelModel;
@class OrgMapsforgeMapScalebarMapScaleBar;
@class OrgMapsforgeMapViewFpsCounter;
@class OrgMapsforgeMapViewFrameBuffer;

@protocol OrgMapsforgeMapViewMapView < NSObject, JavaObject >

- (void)destroy;

- (OrgMapsforgeCoreModelDimension *)getDimension;

- (OrgMapsforgeMapViewFpsCounter *)getFpsCounter;

- (OrgMapsforgeMapScalebarMapScaleBar *)getMapScaleBar;

- (void)setMapScaleBarWithOrgMapsforgeMapScalebarMapScaleBar:(OrgMapsforgeMapScalebarMapScaleBar *)mapScaleBar;

- (OrgMapsforgeMapViewFrameBuffer *)getFrameBuffer;

- (jint)getHeight;

- (OrgMapsforgeMapLayerLayerManager *)getLayerManager;

- (OrgMapsforgeMapModelModel *)getModel;

- (jint)getWidth;

- (void)repaint;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeMapViewMapView)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeMapViewMapView)

#endif // _OrgMapsforgeMapViewMapView_H_
