//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/spec/RSAOtherPrimeInfo.java
//

#ifndef _JavaSecuritySpecRSAOtherPrimeInfo_H_
#define _JavaSecuritySpecRSAOtherPrimeInfo_H_

#include "J2ObjC_header.h"

@class JavaMathBigInteger;

@interface JavaSecuritySpecRSAOtherPrimeInfo : NSObject

#pragma mark Public

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)prime
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)crtCoefficient;

- (JavaMathBigInteger *)getCrtCoefficient;

- (JavaMathBigInteger *)getExponent;

- (JavaMathBigInteger *)getPrime;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySpecRSAOtherPrimeInfo)

FOUNDATION_EXPORT void JavaSecuritySpecRSAOtherPrimeInfo_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaSecuritySpecRSAOtherPrimeInfo *self, JavaMathBigInteger *prime, JavaMathBigInteger *primeExponent, JavaMathBigInteger *crtCoefficient);

FOUNDATION_EXPORT JavaSecuritySpecRSAOtherPrimeInfo *new_JavaSecuritySpecRSAOtherPrimeInfo_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaMathBigInteger *prime, JavaMathBigInteger *primeExponent, JavaMathBigInteger *crtCoefficient) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySpecRSAOtherPrimeInfo)

#endif // _JavaSecuritySpecRSAOtherPrimeInfo_H_
