//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/spec/RSAPrivateCrtKeySpec.java
//

#ifndef _JavaSecuritySpecRSAPrivateCrtKeySpec_H_
#define _JavaSecuritySpecRSAPrivateCrtKeySpec_H_

#include "J2ObjC_header.h"
#include "java/security/spec/RSAPrivateKeySpec.h"

@class JavaMathBigInteger;

@interface JavaSecuritySpecRSAPrivateCrtKeySpec : JavaSecuritySpecRSAPrivateKeySpec

#pragma mark Public

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)modulus
                    withJavaMathBigInteger:(JavaMathBigInteger *)publicExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)privateExponent
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentP
                    withJavaMathBigInteger:(JavaMathBigInteger *)primeExponentQ
                    withJavaMathBigInteger:(JavaMathBigInteger *)crtCoefficient;

- (JavaMathBigInteger *)getCrtCoefficient;

- (JavaMathBigInteger *)getPrimeExponentP;

- (JavaMathBigInteger *)getPrimeExponentQ;

- (JavaMathBigInteger *)getPrimeP;

- (JavaMathBigInteger *)getPrimeQ;

- (JavaMathBigInteger *)getPublicExponent;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySpecRSAPrivateCrtKeySpec)

FOUNDATION_EXPORT void JavaSecuritySpecRSAPrivateCrtKeySpec_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaSecuritySpecRSAPrivateCrtKeySpec *self, JavaMathBigInteger *modulus, JavaMathBigInteger *publicExponent, JavaMathBigInteger *privateExponent, JavaMathBigInteger *primeP, JavaMathBigInteger *primeQ, JavaMathBigInteger *primeExponentP, JavaMathBigInteger *primeExponentQ, JavaMathBigInteger *crtCoefficient);

FOUNDATION_EXPORT JavaSecuritySpecRSAPrivateCrtKeySpec *new_JavaSecuritySpecRSAPrivateCrtKeySpec_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigInteger_(JavaMathBigInteger *modulus, JavaMathBigInteger *publicExponent, JavaMathBigInteger *privateExponent, JavaMathBigInteger *primeP, JavaMathBigInteger *primeQ, JavaMathBigInteger *primeExponentP, JavaMathBigInteger *primeExponentQ, JavaMathBigInteger *crtCoefficient) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySpecRSAPrivateCrtKeySpec)

#endif // _JavaSecuritySpecRSAPrivateCrtKeySpec_H_
